### ISSUE TITLE
dropdown in application does not load plots. 

### ISSUE THREAD

**Issue by riwajsapkota** [dstackai/dstack#10]
1. dstack version = v0.6.dev8, operating system = windows
2.  Ran the following code with *require_apply* = False (see code below)
3. Application does not load when selecting different options from the dropdown, see screenshot below

-------------------code----------------------------------------------------------------------------
```
from datetime import datetime, timedelta

import dstack.controls as ctrl
import dstack as ds
import plotly.graph_objects as go
import pandas_datareader.data as web


def get_chart(symbols: ctrl.ComboBox):
    start = datetime.today() - timedelta(days=30)
    end = datetime.today()
    df = web.DataReader(symbols.value(), 'yahoo', start, end)
    fig = go.Figure(
        data=[go.Candlestick(x=df.index, open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'])])
    return fig


app = ds.app(get_chart, symbols=ctrl.ComboBox(["FB", "AMZN", "AAPL", "NFLX", "GOOG"], require_apply=False))

result = ds.push("faang", app)
print(result.url)

```
----------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/51491390/100523594-f1c31b00-31b1-11eb-9b92-fa747feadbc9.png)

**Comment by peterschmidt85** [comment]
Could you please open Chrome’s Developer Tools, select it’s Network tab and try to reproduce again. Attach the screenshots of the requests “execute” and “poll” from the list of the requests.

**Comment by riwajsapkota** [comment]
![image](https://user-images.githubusercontent.com/51491390/100530323-d297ae00-31f0-11eb-83d5-ce56bb16a6f4.png)
![image](https://user-images.githubusercontent.com/51491390/100530336-f2c76d00-31f0-11eb-9ade-55e7c266e3fd.png)
![image](https://user-images.githubusercontent.com/51491390/100530343-125e9580-31f1-11eb-8a21-e2d39a396994.png)

**Comment by peterschmidt85** [comment]
Must be fixed with the latest version of the server (on stgn).
