### ISSUE TITLE
[Bug]: Can't run a service on dstack Sky because of LetsEncrypt's `too many certificates already issued for "dstack.ai"`

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1004]
`dstack` is using LetsEncrypt for creating SSL certificates when deploying services. LetsEncrypt has a [rate limit](https://letsencrypt.org/docs/rate-limits/).

Because dstack Sky is using the same domain for all users, it may exceed the limit, resulting in a failure to deploy a service:

<img width="1017" alt="Screenshot_2024-03-12_at_2 16 04_PM" src="https://github.com/dstackai/dstack/assets/54148038/e05c13d7-0043-4157-a301-bf0b00c241ac">

## Solution

Add optional support for [ZeroSSL](https://zerossl.com/) (which can be enabled via an environment variable, e.g. `ZEROSSL_API_KEY`) and use it instead of LetsEncrypt when enabled.

## Workarounds:

1. Wait until the rate limit is reset (can be any time later today)
2. [Allow the user to specify a custom domain](https://github.com/dstackai/dstack/issues/997) (not supported yet)

**Comment by jvstme** [comment]
Now we can use ZeroSSL or any other CA that supports ACME with reusable EAB credentials. To use ZeroSSL, set these environment variables when running `dstack server`:
- `DSTACK_ACME_SERVER=https://acme.zerossl.com/v2/DV90`
- `DSTACK_ACME_EAB_KID` and `DSTACK_ACME_EAB_HMAC_KEY` — generate these at https://app.zerossl.com/developer

**Comment by peterschmidt85** [comment]
@jvstme Let's enable it with dstack Sky and deploy to the staging!
