### ISSUE TITLE
Docker pull related issues

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1025]
We've found a few bugs in the dstack-shim for a week. 

**1.** The run gets stuck in the pulling state, but server logs show that the container successfully completed. 

`shim.log` example:
```
2024/03/19 09:14:36 Pulling image
2024/03/19 09:14:39 Creating container
2024/03/19 09:14:39 Running container, id=a42597e3c4ce931eb247238440a184af046fb28577a6c5f8f879a16ba4846313
2024/03/19 09:14:39 Container finished successfully, id=a42597e3c4ce931eb247238440a184af046fb28577a6c5f8f879a16ba4846313
```

This is because the request of the container status comes after the container has finished running.

**2.** The task would also stuck in the pulling state if a large container image took a long time to download. 

`shim.log` example:
```
2024/03/19 05:53:34 Downloading runner from https://dstack-runner-downloads.s3.eu-west-1.amazonaws.com/0.16.3/binaries/dstack-runner-linux-amd64
2024/03/19 05:53:37 close body error: %!s(<nil>)
2024/03/19 05:53:37 Docker: {Shim:{HTTPPort:10998 HomeDir:/root/.dstack} Runner:{HTTPPort:10999 LogLevel:6 Version:0.16.3 DevChannel:false BinaryPath:/tmp/dstack-runner1394720425 TempDir:/tmp/runner HomeDir:/root WorkingDir:/workflow} Docker:{SSHPort:10022 KeepContainer:true PublicSSHKey:ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7h8+EIV0hyXRmJq4xns8tHE3boYw5JShsDuV+RrRwq8LFMk5j4/fsy8xFdMCfhoxD6z7faPODZUaBldtTM8mrcFbWO73Ws/18dXGFdQYOTDUQvzFNNkWMdpM1erSaH39CppvYGEmlt110uhckPtq4aTdvB4Kwtd5SOHHESDPcc5iUiMY/htOMrm/R5jXGq2ASXsZHOq2DsrrqyPLhPtb2eyBYAnyPn8lzO/hjDfYuvxjVI0uHNKIsn25zSHNvNxESofW/bPdQvxrVvxO05u97edtFVH6eHzZPs/wa4HIH1Z7or57GfK2HOPGoOkwHD2dsAPwfWwAPKhHkJiY1jfaP janaab11@dstack
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDf2SSUmYJFa6zdo4oK95p6Y/8sumea6ADGn4lQXzEr/tbbLE5S2t9xOkyaOxsjqjt+8OVGfgPAXbA+A63tZjYiVs3Ur8IsXmCSrS/C1eZEVMkJKzgBPGXOK58goIKZYQVXaaVIASZk1dayi/PWWN2sStjZH71jT6iUe06Sk1GUNJGein+hVA84WIC4Z5frGDRMXfBgGKSIK4KqgDLFMhhJWQC+hTzGfuxLdI6SgwyoF3vk7GjD6VzJH/Z1LKwTW5omTsqb9VbvJdZcPW6fiMcTTfICMhbqyAxuF3jPryG4BzdBMRIBQ/OzIfMIUXZ8r4A43e9twfxGwJaOVtAVSHXt dstack}}
2024/03/19 05:53:38 Pulling image
pullImage error: context deadline exceeded
```

**3.** The current log from the `docker pull` process is unclear. It needs to be enhanced by including additional details and timestamps.

**Comment by TheBits** [comment]
I've been researching the issues.

1. @peterschmidt85 Please check that the credentials are correct
2. `pullImage error: context deadline exceeded` - The download timeout has been reached. I will increase it and will add logs.

**Comment by peterschmidt85** [comment]
Tested with 0.16.5 (dstack Sky). The issue number 2 (too large Docker image, see above) is still reproduced:

<img width="1391" alt="Screenshot 2024-03-27 at 12 11 31" src="https://github.com/dstackai/dstack/assets/54148038/9358d94b-6f5d-44fb-ab78-bd0c4b4a4117">
