### ISSUE TITLE
[Bug]: Environment variables are not available in ssh dev environments

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1028]
### dstack version

master

### Python version

3.11

### Host OS

macOS 13.4

### Host Arch

ARM

### What happened?

This is basically a regression of #481

1. Pass an env variable to a dev environment defined via CLI or run configuration
2. Connect to the dev environment. Run `env` – you'll not see the env variable specified.

The problem does not occur for tasks.

**Comment by peterschmidt85** [comment]
Hmm, I was fixing [some related thing](https://github.com/dstackai/dstack/issues/930) not long ago. Not sure if it's connected. The problem i was fixing only related to `ssh` and `PATH`.

**Comment by peterschmidt85** [comment]
Curious if this worked in previous versions or never worked.

**Comment by r4victor** [comment]
This is most probably because the shim runs `env >> ~/.ssh/environment` when starting the container – the job and environment variables are not available at this point.

**Comment by r4victor** [comment]
So it seems like it haven't been working since the runner/shim refactoring.
