### ISSUE TITLE
[Feature]: Support Python 3.12

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#1029]
### Problem

It is not possible to use Python 3.12 when running jobs with dstack
```shell
$ cat hello.yml
type: task

python: "3.12"
commands:
  - python -c 'print("Hello dstack!")'

$ dstack run . -f hello.yml
1 validation error for RunConfiguration
__root__ -> TaskConfiguration -> python
  '3.12' is not a valid PythonVersion (type=value_error)
```

### Solution

Support Python 3.12

### Benefit

Allow users to benefit from new features and improvements in Python 3.12

### Alternatives

-

### Would you like to help contributing this feature?

Yes

**Comment by peterschmidt85** [comment]
> [!NOTE]
> Currently, Python 3.12 image aren't pre-pulled to AWS/GCP/Azure AMIs. The idea is to see how it affects the startup and UX and get back to this question and either a) pre-pull them; or b) drop the pre-pulling logic entirely.

**Comment by jvstme** [comment]
Python 3.12 is now pre-pulled in `dstack` VM images since version 0.4, added in #1391. This saves about 30 seconds of run startup time on new instances
