### ISSUE TITLE
Update the back link on the stack page

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#103]
The new design according to the sketch:

<img width="534" alt="Screenshot 2021-01-28 at 17 07 36" src="https://user-images.githubusercontent.com/54148038/106165446-6b17c380-618b-11eb-8ddb-43d9ed42ea0e.png">

`Back to Applications` and `Back to Models`

**Comment by olgenn** [comment]
Closes https://github.com/dstackai/dstack/commit/81ca883b1a28cef9ed7b57bddbe8f60a128aa1f4
