### ISSUE TITLE
[Feature]: Provide environment variable values via `env`

### ISSUE THREAD

**Issue by alvarobartt** [dstackai/dstack#1045]
### Problem

I would like to provide the values for environment variables via args in `dstack run`, so that I can tweak those even those are not set, but without exposing those within the file.

Could be related to the recently included #1003

### Solution

I would like to be able to provide e.g. `WANDB_API_KEY=${{ run.args.wandb_api_key }}`

### Benefit

Not having to expose the keys within the `.dstack.yaml` file and not having to define those as environment variables from the VM where `dstack run` is triggered.

**Comment by peterschmidt85** [comment]
@alvarobartt BTW, as a workaround I guess you can set them via `--env VALUE` in `dstack run`. Would that solve it?

**Comment by alvarobartt** [comment]
Yes, that's great, but can I still define those as

```yaml
env:
    WANDB_API_KEY
```

To ensure that the value needs to be provided? i.e. to not obscure those environment variables, and clearly expose those so that users willing to replicate know that those environment variables need to be set in advance? That's the reason I found more convenient to define those and provide those via runtime arg, but I'll try out the approach you mention to see whether that does the work for the intended use case, thanks for the help!

**Comment by peterschmidt85** [comment]
@alvarobartt That is exactly what @spott has implemented in https://github.com/dstackai/dstack/pull/1003. I tried it today and it works like a charm.
If you're using the OSS version, you can already try it with https://github.com/dstackai/dstack/releases/tag/0.17.0rc1
Not deployed to Sky yet

**Comment by peterschmidt85** [comment]
@alvarobartt I suppose this should be available now in both `0.17.0` OSS and dstack Sky. Please re-open if something important is missing.
