### ISSUE TITLE
[Bug]: First option in `dstack run` never used

### ISSUE THREAD

**Issue by alvarobartt** [dstackai/dstack#1046]
### dstack version

0.16.5

### Python version

3.11

### Host OS

macOS

### Host Arch

arm64

### What happened?

Even though the first option of `dstack run` was `azure` and costs 5.63USD, that option is not selected and instead the `gcp` option (third one in the screenshot) is selected instead.

Is that supposed to happen? If that was the case, shouldn't a message be shown like e.g. `option n failed to allocate, falling back to option n+1`?

<img width="1392" alt="image" src="https://github.com/dstackai/dstack/assets/36760800/11a3e3ee-1031-4c07-8289-9656ba64a9aa">

In this case, as you can see I'm trying to allocate a Spot VM with 4 x A100 80 GB, in case you're willing to reproduce, I would assume the issue is that the default behaviour is just falling back to the next option if the current doesn't work, specially when trying to allocate A100 80GB GPUs.

**Comment by peterschmidt85** [comment]
@alvarobartt 
Currently, `dstack` walks over the offers one by one and picks the one that is available at the moment.
Can it be because the first offer wasn't available?

**Comment by alvarobartt** [comment]
Yes that's what I assumed, but was just confused that `gcp` was picked over `azure` when I assumed the first option was being used, but that's fair! Thanks for the clarification!
