### ISSUE TITLE
[Feature]: Add JSON formatter for logging

### ISSUE THREAD

**Issue by TheBits** [dstackai/dstack#1062]
### Problem

Dstack server outputs unstructured logs. Filtering unstructured logs by fields is not efficient in the CloudWatch. Multi-line unstructured logs (stacktrace for example) makes logs hard to understand.

### Solution

Let's add JSON formatter to dstack server. We will be able to filter easily. And structure logs with additional fields.

### Would you like to help us implement this feature by sending a PR?

Yes

**Comment by peterschmidt85** [comment]
@TheBits Please enable the JSON logger handler if the user sets the corresponding environment variable (must be enabled by default in our Docker image). Otherwise, we must use our rich formatting logger handler. 
Let me know if you'll have questions.

**Comment by TheBits** [comment]
@peterschmidt85 I added the `DSTACK_SERVER_LOG_FORMAT` environment variable for selecting the log output format. There are two supported values: `standard` and `json`.
