### ISSUE TITLE
[Bug]: Launching Cudo instances in the in-hyderabad-1 region fails

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1075]
Run `dstack run . -b cudo --region in-hyderabad-1`. The run gets stuck in submitted. The instance in the Cuda UI is shown as Failed. The API doesn't return any errors and the server hangs. This happens only for the  in-hyderabad-1 region. Other regions work.

**Comment by peterschmidt85** [comment]
It seems we reported this to CUDO's support team and got the following response from Andrew:

> I've had the software team confirm that in normal circumstances, if the response indicates the existence of a machine type, it will always be true that such a machine could be created.
>
> The only time that might not be true would be if between getting types and trying to start one, the final stock had become exhausted, but this would be rare.
>
> However, in the specific case of when you were trying to do what you were doing, the site in question had experienced an exhaustion of public IP addresses.
> At the moment, the back-end doesn't handle this particularly gracefully; i.e. you might still be told the machine is available, and be able to make a request to start one, and then it would stall on creation.
>
> We are currently working on making this more fail-safe with some additional software checks before advertising availability, and returning success on a creation attempt.
>
> We're also working with suppliers to ensure they're ahead of resources running out, whether that be addresses or hardware inventory, so there are fewer cases of things running out.

**Comment by peterschmidt85** [comment]
@r4victor Do you think we could implement a workaround? Should I reach back to Andrew? 

cc @Bihan

**Comment by r4victor** [comment]
I observed that create_virtual_machine() request hangs in this case. CudoApiClient should set timeouts on requests.

**Comment by Bihan** [comment]
> @r4victor Do you think we could implement a workaround? Should I reach back to Andrew?
> 
> cc @Bihan

@peterschmidt85 Please let me know if I need to do anything regarding this issue? I have also tried creating VM using Cudo's web console. Even from there it hangs in the case of `in-hyderabad-1 ` and in other locations.

**Comment by peterschmidt85** [comment]
@Bihan The question is whether there is anything we can do to workaround this issue, or if it's a complete blocker that must be fixed by CUDO. Currently, this issue blocks us from using CUDO.

**Comment by Bihan** [comment]
> @Bihan The question is whether there is anything we can do to workaround this issue, or if it's a complete blocker that must be fixed by CUDO. Currently, this issue blocks us from using CUDO.

@peterschmidt85 I think as a workaround we can set timeout and respond to user that machine is not available if VM creation hangs.

**Comment by peterschmidt85** [comment]
@Bihan 
> respond to user that machine is not available

IMO the ideal workaround would be if we treat it as a capacity issue and move on to the next offer.

cc @r4victor

**Comment by Bihan** [comment]
ideal workaround would be if we treat it as a capacity issue and move on to the next offer. 

@peterschmidt85 should I implement this workaround?

**Comment by peterschmidt85** [comment]
> should I implement this workaround?

@Bihan Let's hear back from @r4victor first and then, decide what to do, okay?

**Comment by r4victor** [comment]
I'll take care of it. The plan is:

* Filter out offers from the in-hyderabad-1 region.
* Introduce request timeouts in case this happens for any other reason.
