### ISSUE TITLE
Support multi-node training

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1084]
Currently, dstack supports only one node for running tasks. We want to implement launching multiple jobs per run on multiple interconnected nodes to support multi-node training:

```
type: task
…
nodes: 2
commands: python3 -m torch.distributed.launch \
    --nproc_per_node=${DSTACK_GPUS_PER_NODE} \
    --node_rank=${DSTACK_NODE_RANK} \
    --nnodes=${DSTACK_NODES_NUM} \
    --master_addr=${DSTACK_MASTER_NODE_IP} \
    --master_port=8008 \
    resnet_ddp.py --num_epochs 20
```

This involves the following steps:
1. Introduce a separate cluster entity – interconnected groups of nodes – and include clusters in pools. For multi-node tasks, `dstack run` will use nodes from the same cluster or add a new cluster to the pool. `dstack pool add` will be used for creating new clusters or adding nodes to existing clusters (e.g. by specifying `--cluster`).
2. Support specifying multiple nodes for the task. Create multiple jobs per run. Introduce master/worker jobs. Pass env variables to the runner: DSTACK_NODES_IPS, DSTACK_MASTER_IP, DSTACK_GPUS_PER_NODE, DSTACK_NODE_RANK.
3. Change runs/jobs and instances/pools processing to work with clusters.
4. Support cluster provisioning for backends that support it (AWS, GCP, Azure). Consider first implementing bulk provisioning API (run_jobs/create_instances) for one of the backends (e.g. AWS).

**Comment by peterschmidt85** [comment]
Would be great to make a quick prototype first before implementing - just to make sure torch.distributed.launch is working as we expect (ports, network, IPs, etc), e.g. on an example of AWS instances within the same subnet..

**Comment by peterschmidt85** [comment]
Basically, would be great if possible first make it work with `dstack pool add <ssh>`.
