### ISSUE TITLE
Ability to add your own instances to pools/dstack

### ISSUE THREAD

**Issue by TheBits** [dstackai/dstack#1100]
After we finish [pool support](https://github.com/dstackai/dstack/issues/790), we will be ready to add our own servers to the pool. This is necessary for a particular set of users that have their own bare metal servers.

To add a server, we need to use the `dstack pool add` command in the same way as we add cloud instances with additional arguments:
```
dstack pool add \
    --remote \
    --remote-host 192.168.88.131 \
    --remote-port 22 \
    --ssh-user=root \
    --ssh-identity ~/ssh_key
```

I will explain the new arguments:
`--remote` - Adding a running server
`--remote-host 192.168.88.131` and `--remote-port 22` - Connection detils
`--ssh-user=root` and `--ssh-identity ~/ssh_key.pub` - Credentials for ssh

 To add the server, we need to go through the following steps.
 - connect via ssh to the server
 - install `dstack-shim`
 - add dstack-shim.service to the systemd
 
After install, `dstack-shim` should retrieve server resources and save them to the InstanceModel on the dstack server.
This information about server resources will be provided to the user via "dstack pool ps" command.

------

## SSH semantics
It is necessary to change the name the command to `dstack pool add-ssh` to add a remote instance. The add remote instance command must have the same semantics as the ssh command.

Add support for the next cli arguments:
- [x] Support the destination format `[user@]host` or `ssh://[user@]host[:port]`
- [x] `-l login_name` specifies the user
- [x] `-i key` specifies the private key-containing file.
- [x] `-p port` the connection port

## Improvements
- [x] After running the command, it should output a message that includes the `instance name` of the added remote host.
- [x] Support the argument for the `--region`
- [x] Support the argument for the `--pool`
- [x] Give the newly added remote instance a random name.
- [x] Make a draft documentation. 
- [x] Verify the installation of nvidia-docker.
- [x] Use the `dstack/base` image in `docker run` to verify the output of the `nvidia-smi` command.

## multinode support
- [x] Create two instances on the same network, check that they connect to each other.
- [ ] I need to create a new issue with support for remote instances as a backend for multinode.

## Improvements
- [x] The `add_remote` (`process_instances.py`) function blocks the server. For example, Ctrl-C does not work.
- [ ] Add the `-w` flag. Enabling it should show the process of provisioning the remote instance to the idle state. As an example, it should work as `dstack ps -w`.
- [x] Log a warning that the remote instance failed to provisioning
- [ ] Add multionde documentation
- [x] I can add the same instance two times

**Comment by r4victor** [comment]
@TheBits for multi-node support, dstack also needs to know VMs internal ips.
