### ISSUE TITLE
sklearn model attachment not supported in the server software

### ISSUE THREAD

**Issue by riwajsapkota** [dstackai/dstack#111]
1. dstack version:  0.6.3 dev 5,  OS: Windows, Python version:  3.7.6

None of the previous pushed models or newly pushed models are supported. See attachments. 

![image](https://user-images.githubusercontent.com/51491390/107275573-3d1b6480-6a52-11eb-9af0-8585d574383b.png)
![image](https://user-images.githubusercontent.com/51491390/107275643-53c1bb80-6a52-11eb-806e-89f303814a74.png)

![image](https://user-images.githubusercontent.com/51491390/107274809-35a78b80-6a51-11eb-913b-5bc7275f01b7.png)

**Comment by peterschmidt85** [comment]
Example: https://github.com/dstackai/dstack-examples/blob/master/sklearn/model.py
