### ISSUE TITLE
Add parametrized job queue support

### ISSUE THREAD

**Issue by vood** [dstackai/dstack#120]
Hi, thanks for building dstack. I want to request a feature:

I'm looking for basic work queue orchestrator that will:
1. Receive parametrized job 
2. Add it to a queue
3. Spin up a dstack workflow per each job in a queue
4. API for the job and job queue status. Each job could have some status like queued, processing, failed, or succeeded. 
5. Both input and output parameters (like s3 bucket name, hyperparameters, etc) should be dynamic. 

A use case:
I'd like to build a platform where users can request fine-tuning of models based on their parameters.

**Comment by peterschmidt85** [comment]
This issue is implemented.
It's possible to pass arguments to tasks and configure retry policy!
