### ISSUE TITLE
[Feature]: Configuration for master node network selection

### ISSUE THREAD

**Issue by TheBits** [dstackai/dstack#1209]
### Problem

A job running in multimode mode must correctly identify the IP address of the master node. A master node instance can have multiple network addresses, and we must select the desired address to using it.

### Solution

I suggest adding the `--network` flag to `dstack pool add-ssh` command. Using this option, we can specify which IP-network (and IP-address) to use from those available on the master node.

The master node must store the IP address of the desired network. The workers will receive the address of the master node.

### Workaround

Multinode now works because the master node only has one IP address for the internal network.

### Would you like to help us implement this feature by sending a PR?

Yes

**Comment by peterschmidt85** [comment]
To be honest, I'm couldn't understand how you want to implement it from your issue description.

Where exactly you plan to add the parameter and what the value is accepted and what if it's not passed, etc.

**Comment by peterschmidt85** [comment]
Why `dstack run`? I thought it must be `dstack pool add-ssh`.

**Comment by TheBits** [comment]
Oh, yes, you're right.
