### ISSUE TITLE
 Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

### ISSUE THREAD

**Issue by daoud** [dstackai/dstack#121]
sharing following command as follow:
step-1 : dstack server start
step-2 : it create automatically .dstack folder in my system.
steo-3 :  user: <username>
    token: <token>
    server: http://localhost:8080/api 
step-4 : stop the server
step-5 : run the python file => python filename.py
after running the file, it giving the error:
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/stacks/push (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DA81A4C848>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by peterschmidt85** [comment]
Why do you stop the server before You run you file name.py? The server should be up when you run you application.

**Comment by daoud** [comment]
shall we use 2 command prompt window (one for server and anther for python script)?

**Comment by daoud** [comment]
> Why do you stop the server before you run you filename.py? The server should be up when you run you application.

shall we use 2 command prompt window (one for server and anther for python script)?

**Comment by daoud** [comment]
> Why do you stop the server before you run you filename.py? The server should be up when you run you application.

i am facing error to run same script .
sharing following command as follow:
step-1 : dstack server start (command prompt)
step-2 : it create automatically .dstack folder in my system (first time)
step-3 : 
user: <>
token: <>
server: http://localhost:8080/api
step-4: open the URL on web: http://localhost:8080/auth/verify?user=dstack&code=5ff1e8ed-a740-4a21-95d0-dc9c08f7f20d&next=/
Step-5: http://localhost:8080/applications
step -6: on new command prompt run the script : python loan_prediction.py 
step-7: FYI,  I am using two command prompt : (1) dstack server start (2) python loan_prediction.py
step -8: after executing the  python loan_prediction.py following error
..................
 python loan_prediction.py
training
     Dependents  ApplicantIncome  CoapplicantIncome  ...  Self_Employed_Yes  Property_Area_Semiurban  Property_Area_Urban
0             0             5849                0.0  ...                  0                        0                    1
1             1             4583             1508.0  ...                  0                        0                    0
2             0             3000                0.0  ...                  1                        0                    1
3             0             2583             2358.0  ...                  0                        0                    1
4             0             6000                0.0  ...                  0                        0                    1
..          ...              ...                ...  ...                ...                      ...                  ...
609           0             2900                0.0  ...                  0                        0                    0
610           3             4106                0.0  ...                  0                        0                    0
611           1             8072              240.0  ...                  0                        0                    1
612           2             7583                0.0  ...                  0                        0                    1
613           0             4583                0.0  ...                  1                        1                    0

[614 rows x 12 columns]
output
0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int64
testing
     Dependents  ApplicantIncome  CoapplicantIncome  ...  Self_Employed_Yes  Property_Area_Semiurban  Property_Area_Urban
0             0             5720                  0  ...                  0                        0                    1
1             1             3076               1500  ...                  0                        0                    1
2             2             5000               1800  ...                  0                        0                    1
3             2             2340               2546  ...                  0                        0                    1
4             0             3276                  0  ...                  0                        0                    1
..          ...              ...                ...  ...                ...                      ...                  ...
362           3             4009               1777  ...                  1                        0                    1
363           0             4158                709  ...                  0                        0                    1
364           0             3250               1993  ...                  0                        1                    0
365           0             5000               2393  ...                  0                        0                    0
366           0             9200                  0  ...                  1                        0                    0

[367 rows x 12 columns]
Traceback (most recent call last):
  File "loan_prediction.py", line 55, in <module>
    ds.push("Random_Forest", random, "Random Forest Loan Prediction")
  File "C:\Users\Hanzalah\.conda\envs\ML_env\lib\site-packages\dstack\__init__.py", line 51, in push
    return f.push(meta)
  File "C:\Users\Hanzalah\.conda\envs\ML_env\lib\site-packages\dstack\stack.py", line 150, in push
    return self.send_push(frame)
  File "C:\Users\Hanzalah\.conda\envs\ML_env\lib\site-packages\dstack\stack.py", line 181, in send_push
    res = self.context.protocol.push(self.context.stack_path(), self.context.profile.token, frame)
  File "C:\Users\Hanzalah\.conda\envs\ML_env\lib\site-packages\dstack\protocol.py", line 61, in push
    result = self.do_request("/stacks/push", data, token)
  File "C:\Users\Hanzalah\.conda\envs\ML_env\lib\site-packages\dstack\protocol.py", line 122, in do_request
    response.raise_for_status()
  File "C:\Users\Hanzalah\.conda\envs\ML_env\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error:  for url: http://localhost:8080/api/stacks/push

**Comment by peterschmidt85** [comment]
What is step 3?

**Comment by daoud** [comment]
> What is step 3?

only credential information that are created by dstack (path of config.yaml =>C:\Users\Hanzalah\.dstack). apart form the config.yaml file 3 folder available  (cache, data, files)

**Comment by peterschmidt85** [comment]
Are you sure you didn’t modify your ~/.dstack/config.yaml after it was automatically created?

**Comment by peterschmidt85** [comment]
What I’d suggest you before you try the tutorial from the blog post you found, is following the https://docs.dstack.ai/quickstart

**Comment by peterschmidt85** [comment]
To make sure the problem is not with dstack

**Comment by daoud** [comment]
> Are you sure you didn’t modify your ~/.dstack/config.yaml after it was automatically created?

yes , I didn’t any modification in   ~/.dstack/config.yaml

**Comment by daoud** [comment]
> What I’d suggest you before you try the tutorial from the blog post you found, is following the https://docs.dstack.ai/quickstart

facing same issue . if you don't mind can we connect for few minutes on google meet  or other channel ?

**Comment by peterschmidt85** [comment]
Sure let me paste link here

**Comment by peterschmidt85** [comment]
To join the video meeting, click this link: https://meet.google.com/wzv-npvk-adb

To join by phone instead, dial ‪(DE) +49 30 300195058‬ and enter this PIN: ‪601 206 019#‬

More phone numbers: https://tel.meet/wzv-npvk-adb?pin=2162951793221

**Comment by peterschmidt85** [comment]
Hope all is good now. Please let me know if you see the problem again! Have a great day.
