### ISSUE TITLE
[Bug]: Some providers do not look for offers in every region which is available.

### ISSUE THREAD

**Issue by TheBits** [dstackai/dstack#1210]
### Steps to reproduce

An example for a datacrunch provider:
- Using the web interface, locate the GPU that is available in all regions.
- Run the command `dstack run . -ftask.dstack.yaml --gpu H100`

### Actual behaviour

- Only _two regions_ will be included in the list of offers: ICE-01 and FIN-01

### Expected behaviour

- The list of offers does not contain any offers related to the FIN-02 region. Offers should be available in all regions.

### dstack version

0.18.1

### Additional information

Because the names of the regions are hardcoded in the provider's configurator. Only those offers are searched for. It's not just datacrunch; regions are hardcoded in AWS, for example.
It is recommended to remove the hardocded lists of regions and retrieve them at runtime.

I think that integrating it into gpuhunt is the best solution.
- We can get and cache a list of regions, just as we cache offers.
- We can get regions from offers listed in the catalog.

**Comment by r4victor** [comment]
This situation seems to happen when a provider introduces a new region. This does not happen often so we can include it manually. In any case, we cannot enable a region unknown to dstack automatically since the region may not work (e.g. it doesn't have dstack images).
