### ISSUE TITLE
[Bug]: Instances that are temporarily not available should be skipped during provisioning a job

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1234]
### Steps to reproduce

1. Add an instance, e.g. via `dstack pool add-ssh`, and wait until the instance is shown as `idle`
2. Shutdown the instance manually (via the cloud console or by plugging of the power)
3. Call `dstack run` with `--reuse`

### Actual behaviour

1. The run is assigned to the instance (that is not available at the moment of submission of the run but still shown as `idle`)
2. The run gets stuck in `provisioning`

### Expected behaviour

1. If the instance is temporarily unavailable, mark it with `temproarily_unavailable=true` (and show it in the console/UI)
2. Skip such instances during provisioning new jobs

### dstack version

Any

**Comment by r4victor** [comment]
Especially relevant after #1200. Currently, dstack may resubmit the run to the cloud instance that is no longer available (e.g. was interrupted/deleted). The dstack will remove the instance only after it doesn't hear from the instance for 20m.

**Comment by r4victor** [comment]
@peterschmidt85, any preferences how display instances that are temporarily unavailable? We could use `unavailable` status but it can easily be mistaken with `busy` (both mean unavailable for provisioning). I suggest we show it as `unreachable`.
