### ISSUE TITLE
[Bug]: instances from the pool is always selected no matter what

### ISSUE THREAD

**Issue by deep-diver** [dstackai/dstack#1244]
### Steps to reproduce

1. add `ssh` backend in `default-pool` with an instance spec `60xCPU, 472.172GB, 2xNVIDIA A10 (22.4883GB), 280.578GB(disk).

2. write `dstack.yml` as below:
```yaml
type: task
...
...
resources:
  gpu:
    memory: 40GB
    name: A100
```

3. run `dstack run` command:
```console
$ dstack run . -f deploy.task.dstack.yml --spot-policy spot
```

4. it shows wrong choices to select
```
 #  BACKEND  REGION        INSTANCE       RESOURCES                                                  SPOT  PRICE
 1  ssh      remote        instance       60xCPU, 472.172GB, 2xNVIDIA A10 (22.4883GB), 280.578GB     no    $0        idle
                                          (disk)

 2  gcp      europe-west4  a2-highgpu-1g  12xCPU, 85GB, 1xA100 (40GB), 100GB (disk)                  yes   $1.20582
    ...
```

### Actual behaviour

it shows the `ssh` backend option to choose.

### Expected behaviour

it should not show the `ssh` backend option to choose since it does not meet the requirements.

### dstack version

0.18.1

### Server logs

```shell
no server logs
```

**Comment by jvstme** [comment]
Maybe related to #1230

**Comment by r4victor** [comment]
I think this is because instances that belong to `remote` backend explicitly skip all filters:

https://github.com/dstackai/dstack/blob/c90f1f08aec66a45a1da99a3e057ac5777b290a0/src/dstack/_internal/server/services/pools.py#L366-L369

@TheBits, could you clarify if this is indented or should be removed?
