### ISSUE TITLE
[Docs]: Document possible values of target metrics in auto scaling configuration

### ISSUE THREAD

**Issue by rodrigomeireles** [dstackai/dstack#1279]
### Problem

Currently I can't find in [the documentation](https://dstack.ai/docs/reference/dstack.yml/service/#scaling) which target metrics and values are configurable in the auto scaling settings, this makes the interface impossible to use. The example listed "rps" does not even exist in the docs elsewhere.

### Solution

Document auto scaling configuration.

### Would you like to help us implement this feature by sending a PR?

No

**Comment by jvstme** [comment]
@rodrigomeireles, thank you for opening this issue. RPS (requests per second) is the only target metric we currently support. I agree that we should make it more clear in the docs. @peterschmidt85

**Comment by peterschmidt85** [comment]
@rodrigomeireles Thanks for pointing out this. Indeed, the [scaling](https://dstack.ai/docs/reference/dstack.yml/service/#scaling) property documentation must mention explicitly that `rps` is the only value supported. We'll fix that.
Other than that, are there any issues? Shall we add or fix anything more than just this property documentation?

**Comment by rodrigomeireles** [comment]
> @rodrigomeireles Thanks for pointing out this. Indeed, the [scaling](https://dstack.ai/docs/reference/dstack.yml/service/#scaling) property documentation must mention explicitly that `rps` is the only value supported. We'll fix that.
> Other than that, are there any issues? Shall we add or fix anything more than just this property documentation?

Well, I think the docs could be more transparent about the kind of infrastructure and settings being used when scaling. But I didn't request that because it might be a business decision on your part.

**Comment by peterschmidt85** [comment]
@rodrigomeireles We're 100% interested in making it as transparent as possible.
Let us update the docs and get back to you. Meanwhile, please do share any other feedback! 🙏🏽
