### ISSUE TITLE
Allow to run workflows entirely locally (without the cloud) and push their state to the cloud on-demand

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#129]
There is currently [local mode](https://docs.dstack.ai/examples/#run-locally) that is meant to test-run locally before spinning up cloud resources. This requires AWS to be set up first.

If local mode can work without first setting up AWS (i.e. bypass all AWS operations), this gives user a quick way to get started, i.e. on a brand new machine, with newly installed dstack CLI, and WITHOUT AWS setup yet. This is significantly reduce the barrier of entry to dstack. Currently if AWS is not set up, local mode run fails.

**Comment by peterschmidt85** [comment]
## Motivation

**1. I want to be able to run `dstack` workflows locally even if I don't have a cloud account.** 
 
This way I can try `dstack` easier before I start using it with the cloud. `dstack` will still deliver value by helping versioning artifacts locally.

**2. I want to be able to run workflows locally and store their state only locally too until I decide to push it to the cloud.**
 
When I run a workflow locally, currently `dstack` obligatorily uploads the output artifacts to the cloud. Even for medium-size artifacts (3GB), this takes an inadequately long time. Moreover, as a user, I may not want to upload output artifacts before I'm sure it's needed. This means uploading local artifacts should be always on-demand and never automatic.

## Example 

1. I didn't run `dstack config` and don't have `~/.dstack/config` on my machine

2. I run a workflow with the `--local` flag

`dstack` runs the workflow locally and stores its state locally as well. 

The `dstack` CLI commands should give access to both local and remote workflows.

3. If I locally run a workflow that refers to another local workflow or tag (via `deps`), it should work without problems.

4. Later, I can run the `dstack config` command and configure the cloud.

5. Now, I can push any local run to the cloud, e.g. via `dstack push RUN`. 

This command will upload the local state of the run (incl. artifacts) to the cloud, so other remote workflows
can refer to via `deps`.

**Comment by r4victor** [comment]
Implemented in https://github.com/dstackai/dstack/releases/tag/0.1
