### ISSUE TITLE
Make `dstack ls` non-recursive by default

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#131]
Currently, the `dstack ls` command shows all individual files recursively along with their sizes. 
This is not convenient in case artifacts have many files.

By default, the command should only show the total size per configured artifact path.

Support the following signature:

dstack ls RUN_NAME [SOURCE_FILE] [-R] [-t]

`-R` – Show all individual files recursively (as of now)
`SOURCE_FILE` – Show only the files that start from this prefix
`-t` `--total` - Calculate the total size of the corresponding folder. By default, the sizes for folders should be not shown.

**Comment by sauravsolanki** [comment]
Is anyone working on this? I would love to start with it.

**Comment by sauravsolanki** [comment]
@peterschmidt85 Please assign me this task in case.

**Comment by peterschmidt85** [comment]
@sauravsolanki Assigned to you. 
Please ask questions in Slack if any.
Once ready, please submit a pull request!
