### ISSUE TITLE
[Bug]: cudo backend stuck in instance provisioning state for more than 30 minutes

### ISSUE THREAD

**Issue by smokfyz** [dstackai/dstack#1345]
### Steps to reproduce

Run any task on the cudo backend. I used Sky for testing.

### Actual behaviour

The task starts in several minutes.

### Expected behaviour

The task stucked in instance provisioning state for more than 30 minutes.

### dstack version

0.18.3

**Comment by peterschmidt85** [comment]
@smokfyz Would be cool to see what caused the issue

**Comment by smokfyz** [comment]
The issue was with recent changes related to reusing instances by different users. A `GetAuthorizedKeysPath` method was introduced (https://github.com/dstackai/dstack/pull/1347/files#diff-14a84ab25efd3d4bc3dcfe323c1e92eb4a76f6102c134c78919bd0538a4346ecL91), which hardcoded the user home directory to `/home/{username}`. This was true for most cases except for the root user, who has two options for the home directory: `/root` and `/home/root`.

**Comment by peterschmidt85** [comment]
@smokfyz Thank you! Only CUDO was affected? Do you think there could be problems with other backends?
cc @r4victor

**Comment by smokfyz** [comment]
I ran tasks on GCP, AWS, Azure, RunPod, and VastAI. There weren't any problems with them. Other backends could potentially be affected. It probably makes sense to create integration tests after each release (or PRs), which will run a small task to check if the backends work as expected.
