### ISSUE TITLE
[Bug]: `dstack` doesn't offer idle instances if GPU name is uppercase in requirements

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1352]
**Steps to reproduce:**

1. Defne `.dstack.yml` (e.g. `dev-environment`) with `gpu` set to a name (e.g. `A10`).
2. Invoke `dstack run . -f .dstack.yml` 
3. Stop the run
4. Ensure the instance is `idle`
5. Try `dstack run . -f .dstack.yml --reuse` (or without `--reuse` or pass the name of the instance to `--instance`)

_Reproduced with dstack Sky (0.18.3)_

**Actual behavior:**

The idle instance is not offered

**Expected behavior:**

The idle instance should be offered

**Notes:**

If I edit `.dstack.yml` and change `gpu` to `1`, then the idle instance is offered.

**Comment by jvstme** [comment]
Temporary workaround: specify the GPU name in lowercase, e.g. `a10`
