### ISSUE TITLE
The CLI doesn't prompt to invoke `dstack init` for a private repo

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#136]
Steps to reproduce:

1. Create a new private GitHub repo
2. Clone this repo via `gh repo clone`
3. Create a workflow file (e.g. `echo "Hello, world!"`)
4. Run it via `dstack run`

Expected:

1. `"Hello, world!"` is printed to the output

Reality:

1. No output appears
2. The runner log (in CLoudWatch) shows an exception

```
[TRACE]:GIT checkout error[err authentication required GIT URL https://github.com/peterschmidt85/dstack-demo.git]
[ERROR]:Failed run[err [executor.go:213 executor.(*Executor).runJob] [executor.go:319 executor.(*Executor).prepareGit] authentication required]
```

**Comment by peterschmidt85** [comment]
- [x] The CLI should check if the `dstack init` was invoked on this repo before (the corresponding secret exists). If not, it should prompt the user to invoke `dstack init`. (https://github.com/dstackai/dstack/commit/c910e482c48d193de78b72542c914fad999c52bb)
- [ ] The runner should handle this exception, and update both [`status_code` and `status_description`](https://github.com/dstackai/dstack/issues/130) accordingly.

**Comment by r4victor** [comment]
Seems to be no relevant after https://github.com/dstackai/dstack/releases/tag/0.1
