### ISSUE TITLE
Change visibility of Controls using other Controls

### ISSUE THREAD

**Issue by q-viper** [dstackai/dstack#137]
## Use checkbox to hide/show select control. 
* dstack version: 0.6.4

I am trying to visualize sales data from [here](https://www.kaggle.com/c/demand-forecasting-kernels-only/data?select=test.csv) and I want to show a visualization either for each year(different figures) or for all years (in single figure). For this, I am willing to use checkbox and when it is selected, then show the `Years` select control else hide it.

![image](https://user-images.githubusercontent.com/35986908/110450405-44826c00-80eb-11eb-9388-294bedfb4613.png)

**Comment by peterschmidt85** [comment]
Depends on #104
