### ISSUE TITLE
[Bug]: Cannot use `remote` instances if no backends are configured

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#1399]
### Steps to reproduce

1. Configure `~/.dstack/server/config.yml` without backends
   ```yaml
   projects:
   - name: main
     backends: []
   ```
1. Start `dstack server`
1. Add a remote instance
   ```shell
   dstack pool add-ssh ubuntu@10.10.10.10 -i dstack.key
   ```
1. Try running any configuration on the remote instance

### Actual behaviour

The instance is suggested in the offers list, but the run is not submitted
```
> dstack run .
 Configuration          .dstack.yml                    
 Project                main                           
 User                   admin                          
 Pool                   default-pool                   
 Min resources          1..xCPU, 1GB.., 100GB.. (disk) 
 Max price              -                              
 Max duration           6h                             
 Spot policy            on-demand                      
 Retry policy           no                             
 Creation policy        reuse-or-create                
 Termination policy     destroy-after-idle             
 Termination idle time  5m                             

 #  BACKEND  REGION  INSTANCE  RESOURCES                   SPOT  PRICE       
 1  ssh      remote  instance  2xCPU, 15GB, 42.6GB (disk)  no    $0     idle 

Continue? [y/n]: y
No backends configured
```

### Expected behaviour

Runs are submitted to the remote instance.

### dstack version

0.18.4

**Comment by r4victor** [comment]
We used to have this check long before ssh instances had been introduced:

https://github.com/dstackai/dstack/blob/638e38d89856c679ed25f61d04ed00ee34564a34/src/dstack/_internal/server/services/runs.py#L413-L414

It seems like we should simply drop this check now and let user submit runs even if there are no backends configured. An appropriate error message can be set if there are no backends/pool instances at the moment of processing.
