### ISSUE TITLE
Confusing UI when opening an application without opening access URL first

### ISSUE THREAD

**Issue by HarshInvader** [dstackai/dstack#14]
The resulting rendered application looks broken when this access URL generated in the terminal on running `dstack server start` is **not entered** in the browser before accessing the application-  

<img width="849" alt="Untitled 3" src="https://user-images.githubusercontent.com/15952266/100613593-cfa8d480-333a-11eb-8101-5da157e12f65.png">

<img width="1440" alt="Untitled 0" src="https://user-images.githubusercontent.com/15952266/100613614-d7687900-333a-11eb-9734-06501e9b3d6a.png">

It would help to have an error or warning in such a case, as opening the localhost in a new browser or inside an incognito window in the browser would mean having to paste the access URL in it again, which the user can forget to do.

**Comment by peterschmidt85** [comment]
Fixed with the latest commit.
Delete the `server` section on the top level in `~/dstack/config.yaml` and restart the server to try again.
