### ISSUE TITLE
Allow controls if needed overflow the specified rowspan

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#140]
Example 1:
We have a Markdown with rowspan=1 but the content of the Markdown needs more space. Allow the Makrdown to take more space vertically. 
Example 2:
We have an Uploader with rowspan=1 and multiple files attached so the files need more space to render. Allow the Uploader to take more space vertically. 
Example 3:
We have a Select with colspan=6 and rowspan=1 and multiple values selected so all of them do not fit one row. Allow the Select to take more space vertically. 

In all these cases, other controls in the same row remain unchanged. 

See example:
![example](https://user-images.githubusercontent.com/54148038/110484285-cf169b80-80ea-11eb-92ef-a09798170acb.png)

**Comment by olgenn** [comment]
Exemple 3: implement in task https://github.com/dstackai/dstack/issues/106
