### ISSUE TITLE
Add the control plane UI

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1419]
Currently, `dstack` only offers CLI and API to manage projects, users, runs, etc. Moreover, even the CLI doesn't allow to manage users and projects.  If `dstack` is used by an organization (which is the main use case), teams need a convenient UI to manage projects, users, runs, etc.

Currently, such a UI is only included in [dstack Sky](https://sky.dstack.ai/)  and the open-source users of `dstack` cannot use similar features. For organizations, this is a blocker to adopt the open-source version.

The source code of the control plane UI should be moved to this repo and the build/release workflow should be updated accordingly to bundle the static files into the release.

Note, if `dstack` is  launched from the sources (or pip install from GitHub), it should work as now - redirect to the Swagger UI.

**Comment by r4victor** [comment]
Closed by #1524
