### ISSUE TITLE
[Bug]: Support for Proxy in the Network

### ISSUE THREAD

**Issue by ulhaqi12** [dstackai/dstack#1466]
### Problem

I am using dstack on a local machine and trying to run a job on a remote VM instance having GPU.

There is a proxy in the network for which I must set http_peroxy, https_proxy variables to access the internet. The dstack.shim daemon wasn't able to access the internet so I set the proxy variables for it using the following command:

```
$ sudo systemctl edit dstack-shim.service

Copied the following content in that file and saved it:

[Service]
Environment="HTTP_PROXY=http://your.proxy.server:port"
Environment="HTTPS_PROXY=https://your.proxy.server:port"
Environment="NO_PROXY=localhost,127.0.0.1"
```

After this dstack.shim daemon was working fine but now the container that dstack.shim daemon is running (dstackai/base:py3.11-0.4-cuda-12.1) doesn't have proxy variables. How can I set proxy variables for the image it is pulling from Dockerhub?

### Would you like to help us implement this feature by sending a PR?

Yes

**Comment by peterschmidt85** [comment]
@ulhaqi12 Thank you for reporting this one! Please let us take a look and get back to you with an update shortly!

**Comment by peterschmidt85** [comment]
@ulhaqi12 this issue is fixed in https://github.com/dstackai/dstack/releases/tag/0.18.9
Please give a try and let me know if it works now!
