### ISSUE TITLE
[UX] Support `nvcc: True` for run configurations so `dstack` uses a base Docker image with `nvcc`

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1470]
This can be an alternative to `conda install cuda`.

UPDATE:

- [x] Add a script that builds `devel` versions of the `dstackai/base` Docker image
- [x] Run the script and build the actual images for the current Docker image version (0.4): https://hub.docker.com/r/dstackai/base/tags?page=&page_size=&ordering=&name=devel
- [ ] Introduce `nvcc: bool` property with the base run configuration model class, and update the logic of choosing the base Docker image name

**Comment by r4victor** [comment]
@peterschmidt85, `nvcc` is not allowed when a custom `image` is specified?

**Comment by peterschmidt85** [comment]
@r4victor Yup, just like `python`
