### ISSUE TITLE
[UX] Change the default `creation_policy` from `reuse_or_create` to `reuse`

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1482]
Based on experience of using `dstack apply`, realized that creation of new fleets should always be explicit. By default, `dstack` should use the existing fleets. This makes it more predictable and much easier to explain.

To ensure the transition for existing users, in case `dstack appy` cannot find capacity and the no creation policy is specified, show a message: e.g. 

```shell
Pass `--reuse_or_create` to ` dstack appy` or set `creation_policy` to `reuse_or_create` in the configuration."
```

**Comment by peterschmidt85** [comment]
The only problem with this so far is that we have backends that do not support fleets, incl. RunPod, Kubernetes, Vast.ai

**Comment by r4victor** [comment]
@peterschmidt85, I suggest we close this for now.
