### ISSUE TITLE
Change value of one control from handler of another control.

### ISSUE THREAD

**Issue by q-viper** [dstackai/dstack#152]
**Use Case**
* I want my app to have select control whose items will be the columns of **uploaded CSV file**. (I think this is possible with preloaded data only right now.)
* I want to use this feature to show visualization based on the select's value.

**Simple Code**
```python
dapp = ds.app()
select=dapp.select(label="Select one", items=["Sunday", "Monday"])
day = dapp.input(label="Enter which day to add?")

def handler(self, select, day):
    self.label = f"Today is {select.value()}"
    if day.text:
        l=select.items
        l.append(day.text)
        select.items=l
        self.label=f"New items {select.items}"
dapp.output(handler=handler, depends=[select, day], require_apply=True)
dapp.deploy("Dapp")
```
* In above code, I want to add the value of `day.text` into select's items and show that value as the new option of select.

**Comment by peterschmidt85** [comment]
Currently, it's not possible to change the state of control from a handler to another control. No, if you want one control to change depending on another one, you have to use the control's own handler.

I will rename the issue
