### ISSUE TITLE
[UX]:  Add `dstack attach` command

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#1533]
### Problem

It's currently possible to (re-)attach to a running job via `dstack logs --attach RUN_NAME`; this command not only forwards logs to the client, but also forwards ports, which may be unexpected behavior if the user hasn't read the help carefully. `dstack attach` would have a more clear semantics.

### Solution

Add `dstack attach [--host HOST] RUN_NAME` command.

### Would you like to help us implement this feature by sending a PR?

No

**Comment by peterschmidt85** [comment]
The command should also allow to override port mapping via `--port REMOTE:LOCAL`
