### ISSUE TITLE
Introduce default permissions

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1559]
At the moment we don't have granular permission. However, we want to be able to configure the following permissions defaults via environment variables:

- `DSTACK_USER_CAN_CREATE_PROJECTS` – Whether a user is allowed to create new projects (True by default)
- `DSTACK_USER_CAN_CREATE_GATEWAYS` – Whether a user (not a project or global admin) is allowed to create gateways (True by default)
- `DSTACK_USER_CAN_CREATE_ON_PREM_FLEETS` – Whether a user (not a project or global admin) is allowed to create on-prem fleets (True by default)

**Comment by olgenn** [comment]
@peterschmidt85 Maybe, do we need a permission: `DSTACK_USER_CAN_DELETE_PROJECTS` ?

**Comment by peterschmidt85** [comment]
@olgenn If a user can create a project, then it can delete that project as an owner
