### ISSUE TITLE
[UX]: Resize chat input field based on content 

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#1562]
### Current

In the model chat, the input field can only fit 3 lines of text. Working with longer messages is inconvenient, as it requires scrolling.

![dstack](https://github.com/user-attachments/assets/1e50ba79-ed6d-47c4-99a8-1b4760060512)

The "System" field also cannot fit much text unless resized manually.

### Proposed

Adjust both fields' height automatically based on content, the same way as in common messaging apps. Forbid resizing manually.

![slack](https://github.com/user-attachments/assets/037c4ae1-a076-4966-8fdd-5556badfb4af)

**Comment by olgenn** [comment]
Completed in https://github.com/dstackai/dstack/pull/1825

**Comment by jvstme** [comment]
@olgenn, thanks, this looks much more user-friendly. A few additional comments though:
- The issue also proposed to forbid resizing manually (by dragging the bottom-right corner). Do you think it makes sense? I think it's usually forbidden in similar apps. otherwise resizing can lead to layouts that don't look right:
    
    ![1](https://github.com/user-attachments/assets/faa28a42-b5cc-46da-be28-4bfa7652521c)

- The issue also proposed doing the same for the "System" input field on the left: forbid resizing manually, resize automatically based on content. I think this field is less critical but maybe we could apply the same logic to it for consistency?

- Can we limit the max height of the message input field to avoid the messages area getting too small?

    
    ![video](https://github.com/user-attachments/assets/e8e76c3d-069f-4230-9e8c-176bbfeddc0a)

**Comment by jvstme** [comment]
@olgenn, sorry, just one last comment. Could we restore the initial input size after the message is sent? Currently it stays expanded until you type something in it.
![Screenshot from 2024-10-18 16-53-58](https://github.com/user-attachments/assets/5c784fe1-44b1-4d8a-b6c5-285b0088f9f9)
