### ISSUE TITLE
`dstack apply` should be in the attached mode by default for any configuration type

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1571]
Thus should include also volumes, gateways, and fleets.

Currently, the command exits immediately, and I have to wait and check from time to time to see whether it was successful.

1. For any type of configuration, it should display a table (similar to `dstack ps -w`)
2. For runs, the CLI should detach after the run is finished.
3. For other configurations, the CLI should detach once provisioning is finished.

**Comment by r4victor** [comment]
So far the "attach" mode is implemented for:

* [x] runs
* [x] fleets
* [x] volumes
* [x] gateways
