### ISSUE TITLE
Use all available RunPod regions by default

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#1573]
### Current

The RunPod backend only uses a [fixed set](https://github.com/dstackai/dstack/blob/3b9910ef21114ff0e307fff382498ba1982ca853/src/dstack/_internal/server/services/backends/configurators/runpod.py#L25) of regions by default.

```py
REGIONS = [
    "CA-MTL-1",
    "EU-NL-1",
    "EU-RO-1",
    "EU-SE-1",
    "EUR-IS-1",
    "EUR-IS-2",
    "EUR-NO-1",
    "US-OR-1",
]
```

This leads to poorer GPUs availability, e.g. NVIDIA H100 NVL (94GB) is only available in US-KS-2 that is not used by default.

### Proposed

Allow using all existing regions unless a specific set of regions is configured in `.dstack/server/config.yml`.

**Comment by r4victor** [comment]
Note that the fix introduced in #1757 requires the backend config to be updated to use all regions.
