### ISSUE TITLE
Inform users that local workflows take a long time on the first run because of the image pull

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#159]
Users may wait several minutes when they run local workflows for the first time because of the image pull. Right now it leaves bad first experience since users have no clue why `dstack run` takes so long.
 
We need to show a download progress bar or warm about this.

**Comment by neonwatty** [comment]
I was just wondering about this!  

My first time running the local example

```yaml
type: dev-environment
setup:
  - pip install -r requirements.txt
ide: vscode
```

via ```dstack run .``` returned very little output in CLI.  I thought the runner was hanging (was probably pulling).

After restarting and trying again it looks like there's some indication of pulls (e.g., vscode extension), and then after an ssh link to open in vsc desktop ( 👍  ).

I think in general - more verbosity for the CLI when using local would be nice.  imo too much might be better, as local testing is the first user experience.
