### ISSUE TITLE
Set up server tests against Postgres

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1622]
dstack supports SQLite and Postgres as the server database, but pytest tests are currently configured to run only against SQLite. Tests against Postgres should also be automated to minimize manual testing.

**Comment by peterschmidt85** [comment]
Maybe using [testcontainers](https://testcontainers-python.readthedocs.io/en/latest/) ?

**Comment by r4victor** [comment]
Closed by #1628
