### ISSUE TITLE
[Bug]: Dstack says server failed, but server is running inside the container with no errors

### ISSUE THREAD

**Issue by Stealthwriter** [dstackai/dstack#1648]
### Steps to reproduce

This is my yaml, its a sentiment analyses server, basically huggingface wrapper with fastapi server

type: service
name: deberta-sentiment-analyses-server
python: "3.10"

termination_policy: destroy-after-idle
termination_idle_time: 300m
backends: [runpod]
nvcc: true

env:
  - HF_TOKEN=hidden
  - GITHUB_TOKEN=hidden
  - REPO_URL= any repo that runs uvicorn server (not docker image)

port: 8000

replicas: 2

resources:
  gpu: 24GB
  disk:
    size: 100GB

commands:
  - echo "Starting setup process..."
  - apt update && apt upgrade -y
  - git clone https://${GITHUB_TOKEN}@${REPO_URL}
  - cd project
  - pip install --upgrade torch
  - pip install --upgrade fastapi pydantic transformers accelerate uvicorn sentencepiece protobuf bitsandbytes huggingface_hub
  - pip install --upgrade flash-attn
  - huggingface-cli login --token $HF_TOKEN
  - echo "Setup process completed."
  - echo 'Starting server...'
  - python server.py

### Actual behaviour

The server starts inside the container but then in dstack dashboard it says failed, I try to send requests it works fine, for some time, then dstack shutdown the instance

![image](https://github.com/user-attachments/assets/65d88839-dbcf-4e46-9875-24d702cca277)

Also when I do dstack apply -f service.yaml, when its provisioning it takes some time then this error comes up:

servicename provisioning completed (running)                                                                             
Service is published at https://servicename .example.com       (I changed domain name to hide my own)                                                     

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\maher\AppData\Local\Programs\Python\Python312\Scripts\dstack.exe\__main__.py", line 7, in <module>       
  File "C:\Users\maher\AppData\Local\Programs\Python\Python312\Lib\site-packages\dstack\_internal\cli\main.py", line 75, in main
    args.func(args)
  File "C:\Users\maher\AppData\Local\Programs\Python\Python312\Lib\site-packages\dstack\_internal\cli\commands\apply.py", line 70, in _command
    configurator.apply_configuration(
  File "C:\Users\maher\AppData\Local\Programs\Python\Python312\Lib\site-packages\dstack\_internal\cli\services\configurators\run.py", line 147, in apply_configuration
    if run.attach(bind_address=bind_address):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\maher\AppData\Local\Programs\Python\Python312\Lib\site-packages\dstack\api\_public\runs.py", line 293, in attach
    self._ssh_attach.attach()
  File "C:\Users\maher\AppData\Local\Programs\Python\Python312\Lib\site-packages\dstack\_internal\core\services\ssh\attach.py", line 138, in attach
    raise SSHError("Can't connect to the remote host")
dstack._internal.core.errors.SSHError: Can't connect to the remote host

### Expected behaviour

when uvicorn runs dstack should change state of the service to running not failed.

### dstack version

I'm using the docker image, 

### Server logs

```shell
{"message": "run(3e45c4)servicename : run status has changed RUNNING -> TERMINATING", "logger": "dstack._internal.server.background.tasks.process_runs", "timestamp": "2024-09-02 08:39:43,728", "level": "INFO"}
{"message": "job(6a1b17)servicename : instance 'servicename ' has been released, new status is TERMINATING", "logger": "dstack._internal.server.services.jobs", "timestamp": "2024-09-02 08:39:45,230", "level": "INFO"}
{"message": "job(6a1b17)servicename : replica is unregistered from service 3e45c4704d414a9783da95cc2f7bc321", "logger": "dstack._internal.server.services.gateways", "timestamp": "2024-09-02 08:39:45,372", "level": "INFO"}
{"message": "job(6a1b17)servicename : job status is FAILED, reason: INTERRUPTED_BY_NO_CAPACITY", "logger": "dstack._internal.server.services.jobs", "timestamp": "2024-09-02 08:39:45,372", "level": "INFO"}
{"message": "Instance servicename  terminated", "instance_name": "servicename ", "instance_status": "terminated", "logger": "dstack._internal.server.background.tasks.process_instances", "timestamp": "2024-09-02 08:39:51,377", "level": "INFO"}
```

**Comment by peterschmidt85** [comment]
@Stealthwriter Does it happen only when you run a service or also happen when you run a dev environment?

**Comment by Stealthwriter** [comment]
I didn't try on dev enviroment yet, I will try to today

**Comment by Stealthwriter** [comment]
It was related to the spot being shutdown by server

**Comment by r4victor** [comment]
Closing as it should not be relevant after #962
