### ISSUE TITLE
[Feature]: spot_policy should be by default set to on-demand

### ISSUE THREAD

**Issue by Stealthwriter** [dstackai/dstack#1650]
### Problem

runnpod is shutting down servers after like 10 minutes because they have many users, so spot policy should be always on demand unless user wants otherwise then he can change it.

spot_policy: on-demand

### Would you like to help us implement this feature by sending a PR?

Yes

**Comment by peterschmidt85** [comment]
I tend to agree. Using spot should be explicit; it’s unexpected that the default behavior is `auto-spot`.

**Comment by r4victor** [comment]
@Stealthwriter, the default policy will be `on-demand` for all types of runs with the next dstack release.

**Comment by r4victor** [comment]
@peterschmidt85, now when spots require explicit spot policy, I think we need to elaborate more in the docs on how and when spots should be used since they are still great for many use cases and much cheaper (e.g. a section in Protips).

**Comment by peterschmidt85** [comment]
@r4victor Yup, will update docs!

**Comment by Stealthwriter** [comment]
great thanks!
