### ISSUE TITLE
[UI] Revert the list of projects and users in Administration

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1667]
Currently, the list of projects and users show newer entries in the end. It's more convenient to see new entries at the beginning and older entries at the end.

**Comment by r4victor** [comment]
Note: the backend should add sorting to the API or provide the field for the UI to sort by.

**Comment by r4victor** [comment]
@olgenn @peterschmidt85 seeing oldest projects/users on top can be useful as well, so I suggest we add a UI option to sort from oldest to newest and from newest to oldest.
