### ISSUE TITLE
[UX] There is no `--detach` anymore with `dstack apply`

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1671]
```
dstack apply --help
Usage: dstack apply [--project NAME] [-h [TYPE]] [-f FILE] [--force] [-y]

Options:
  --project NAME        The name of the project. Defaults to $DSTACK_PROJECT
  -h, --help [TYPE]     Show this help message and exit.
  -f, --file FILE       The path to the configuration file. Defaults to $PWD/.dstack.yml
  --force               Force apply when no changes detected
  -y, --yes             Do not ask for confirmation
```

**Comment by jvstme** [comment]
It is still there, just not shown in `--help` by default because it is not relevant for every configuration type. See `--help` for a run configuration type.
```shell
> dstack apply --help dev-environment
Usage: dstack apply [--project NAME] [-h [TYPE]] [-f FILE] [--force] [-y] [-n RUN_NAME] [-d] [--max-offers MAX_OFFERS] [-e KEY[=VALUE]] [--gpu SPEC]
                    [--disk RANGE] [--profile NAME] [--max-price PRICE] [--max-duration DURATION] [-b NAME] [-r NAME] [--instance-type NAME]
                    [--pool POOL_NAME | --reuse | --dont-destroy | --idle-duration IDLE_DURATION | --instance NAME]
                    [--spot | --on-demand | --spot-auto | --spot-policy POLICY] [--retry | --no-retry | --retry-duration DURATION] [-p MAPPING] [--host HOST]

Optional Arguments:
  --project NAME        The name of the project. Defaults to $DSTACK_PROJECT
  -h, --help [TYPE]     Show this help message and exit.
  -f, --file FILE       The path to the configuration file. Defaults to $PWD/.dstack.yml
  --force               Force apply when no changes detected
  -y, --yes             Do not ask for confirmation
  -n, --name RUN_NAME   The name of the run. If not specified, a random name is assigned
  -d, --detach          Do not poll logs and run status

[... etc ...]
```

**Comment by peterschmidt85** [comment]
@r4victor Shall we make help not configuration specific? I remember we wanted to do this. cc @jvstme

**Comment by r4victor** [comment]
@peterschmidt85, do you suggest displaying Options for all configuration types? I think it would be too verbose. We could probably mention explicitly that `--help` accepts configuration types in the `dstack apply --help` output.

**Comment by peterschmidt85** [comment]
~~@r4victor Why not show all parameters by default but if the user specified `-t TYPE` or `-f FILE`, then filter. It's a lot easier to use IMO.~~

~~On a related note, I thought about the same - show on https://dstack.ai/docs/reference/dstack.yml/ all options but let the user filter by type if needed. Currently when a user ask about a common property I have to send a link to a specific configuration even though the user could be interested in another configuration.~~

As soon as we implement #1571, `-d` will be shown without specifying the configuration.
