### ISSUE TITLE
[Bug]: Adding on-prem node/instance to two different fleets shouldn't be allowed

### ISSUE THREAD

**Issue by james-boydell** [dstackai/dstack#1699]
### Steps to reproduce

Create a fleet with an on-prem node/instance. Change the name of the fleet in the config and apply. The on-prem node will now be a part of two different fleets. 

### Expected behaviour

When adding a node/instance to a fleet, it should check if that node/instance is already part of a fleet

### dstack version

0.18.13 and 0.18.14rc1

**Comment by r4victor** [comment]
Closed by #1938
