### ISSUE TITLE
[Bug]: `--replica` and `--job` are not respected in `dstack logs --attach`

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#1726]
### Steps to reproduce

Run a multi-node task or a multi-replica service.

```shell
> cat tasks/node-rank.dstack.yml
type: task
name: node-rank
nodes: 2
commands:
  - echo I am node $DSTACK_NODE_RANK
  - sleep infinity

> dstack apply -f tasks/node-rank.dstack.yml --detach -y
```

Attach to the first job or replica using `--job` and/or `--replica`.

```shell
> dstack logs --attach node-rank --job 0
```

Attach to the other.

```shell
> dstack logs --attach node-rank --job 1
```

### Actual behaviour

In both cases, `dstack` CLI attaches to the same job.
```shell
> dstack logs --attach node-rank --job 0
I am node 0
```
```shell
> dstack logs --attach node-rank --job 1
I am node 0
```

### Expected behaviour

`dstack` CLI attaches to the specified job.
```shell
> dstack logs --attach node-rank --job 0
I am node 0
```
```shell
> dstack logs --attach node-rank --job 1
I am node 1
```

### dstack version

master

### Additional information

`dstack logs` without `--attach` does show correct logs.
```shell
> dstack logs node-rank --job 0
I am node 0
> dstack logs node-rank --job 1
I am node 1
```

**Comment by r4victor** [comment]
Should not be relevant after #1733 that replaced `dstack logs --attach` with `dstack attach --logs`. The bug is fixed in `dstack attach`.
