### ISSUE TITLE
[Hacktoberfest 2024] How to contribute

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1735]
Hacktoberfest is a great chance to contribute to your favorite open-source projects! Join us in improving `dstack` throughout October, starting on the 1st.

> [!NOTE]
> ☁️ Every contributor whose PR is merged will receive GPU credits to use with [dstack Sky](https://sky.dstack.ai/) for AI development! Read below for details.
 
##  How do I get started?

> [!WARNING]
> Before you start, ensure you understand dstack and have tried it using your own cloud account or an on-prem machine with dstack's SSH fleets. This step is essential for any contribution; skipping it makes contributions meaningless.

1. Join [Discord](https://discord.gg/u8SmfwPpMd)
2. In case you haven't used `dstack` before, ensure to install it, and give it a try. In case you have questions about `dstack`, make sure to ask them in Discord.
3. Read [CONTRIBUTING.md](https://github.com/dstackai/dstack/blob/master/CONTRIBUTING.md)
4. Ensure you've set up the development environment and know how to run `dstack` from sources.  In case you have questions about `dstack`, make sure to ask them in Discord.
5. Look at the list of some of the issues you can help with below. Pick an issue. Comment the issue with any questions or suggestions. Ensure you understand how it can be implemented.

### Minor

- [x] #1626
- [x] #1471
- [x] #1461
- [x] #1385
- [x] #1379
- [x] #1205
- [x] #821
- [x] #1623
- [x] #1748
- [x] #1749
- [x] #1750
- [x] #1751

### Major

- [x] #1155
- [x] #1664
- [x] #1573
- [x] #1239
- [x] #1752
- [x] #1753
- [x] #1787

### Advanced

- [x] #1747
- [x] #1495

### Can't find an issue?

Feel free to create your own issues to improve `dstack`—whether it’s usability, new features, better docs, or cool examples.

With your help, we'll be adding more issues to the list each week.

## Bounties

* Minor issue – $15
* Major issue – $100
* Advanced issue – $500

> [!WARNING]
> Bounties apply only to quality contributions reviewed and merged by the project's maintainers. If you're interested in joining the reviewer team, please reach out.

**Comment by bikash119** [comment]
Created a new issue #1759. Will raise PR soon.

**Comment by IshuSinghSE** [comment]
> Minor issue – $15
> Major issue – $100
> Advanced issue – $500
> Warning
> 
> Bounties apply only to quality contributions reviewed and merged by the project's maintainers. If you're interested in joining the reviewer team, please reach out.

Could anyone tell me that, How would I receive those GPU credits/bounty ?
My two PR #1626 & #1573  had been merged!

**Comment by peterschmidt85** [comment]
@IshuSinghSE Just added $30 credits to your user on dstack Sky! You can use it on cloud GPU! 
Once again, thank you so much for your contribution! Would love you to contribute more!

**Comment by IshuSinghSE** [comment]
> @IshuSinghSE Just added $30 credits to your user on dstack Sky! You can use it on cloud GPU! Once again, thank you so much for your contribution! Would love you to contribute more!

It's great to contribute to dstackai, Nice to collaborate, Thank you so much!
