### ISSUE TITLE
[Bug]: The "dstack version" plate travels around the screen when scrolling

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#1743]
### Steps to reproduce

1. Open `https://sky.dstack.ai/projects/<any-project>` or any other long page.
2. Try scrolling the page.

### Actual behaviour

![video](https://github.com/user-attachments/assets/5b62cd34-e850-4bed-a690-33244f30cb8a)

### Expected behaviour

The "dstack version" plate is fixed in place and never intersects other elements.

### dstack version

0.18.16

### Additional information

I also think the word "dstack" should be styled in all lowercase.

**Comment by r4victor** [comment]
This should be fixed in master https://github.com/dstackai/dstack/commit/f21021ee89fa3c72bd132152e51eadf1c1b2e21c
