### ISSUE TITLE
[Examples] Add NVIDIA Nim example

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1748]

**Comment by AKASH722** [comment]
Hi @peterschmidt85 ,

I’ve worked with NVIDIA Nim before and would love to take on this issue. Could you please assign it to me?

**Comment by peterschmidt85** [comment]
> Hi @peterschmidt85 ,
> 
> I’ve worked with NVIDIA Nim before and would love to take on this issue. Could you please assign it to me?

Would be great!

We'd like to have it as a separate example under the Deployment category (in addition to other categories such as Fine-tuning, Accelerators, etc.).

The example should feature most essential information around using NIM with dstack.

Note, `dstack` allows to use NIM with both tasks and services. Should we show both, also explaining briefly the difference?

**Comment by peterschmidt85** [comment]
@AKASH722 Contributing to documentation might be tricky as we don't explain how to do this. Let me know if you need help with it.

**Comment by peterschmidt85** [comment]
The sourcecode must be in examples/examples/deployment/nim/README.md (it's copied to the docs when docs are built). See other cards on https://dstack.ai/examples/ to follow the structure and style.

**Comment by AKASH722** [comment]
Thanks, @peterschmidt85!

I’ll add the example to examples/examples/deployment/nim/README.md and follow the structure from dstack. I’ll include both tasks and services, with a brief explanation.

I’ll reach out if I need help with the docs.

**Comment by ishpreet36752** [comment]
@peterschmidt85 do you need all the examples in the frontend UI of the website here - https://dstack.ai/examples/ ?
If yes I would like to make changes

**Comment by r4victor** [comment]
#1853
