### ISSUE TITLE
[Examples] Add GitHub Actions example

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1749]

**Comment by Sofiyan-coder** [comment]
Hi @peterschmidt85  , could you please assign this issue to me? I'd love to contribute and start my open-source journey with this project!

**Comment by peterschmidt85** [comment]
@Sofiyan-coder Go ahead and submit the PR! In case of questions, please let me know! Before you work on it, it's essential that you understand how the tool works, etc!

**Comment by shradiphylleia** [comment]
@peterschmidt85 I wish to understand the scope of this issue. If you want the contributor to add a GitHub workflow such as maybe welcoming first-time contributors, run some tests or maybe trigger a workflow. the title "example" is a bit ambiguous here(atleast to me) 
thanks.

**Comment by peterschmidt85** [comment]
@shradiphylleia The scope is to show how to use dstack from inside GitHub actions, e.g. to submit tasks that require GPU.

**Comment by shradiphylleia** [comment]
@peterschmidt85 if the issue can be assigned to multiple people. Please do assign it to me.

**Comment by peterschmidt85** [comment]
> @peterschmidt85 if the issue can be assigned to multiple people. Please do assign it to me.

No assignment is needed if you want to submit a PR!
