### ISSUE TITLE
[Examples] Add TGI example

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1751]

**Comment by theharshdadhich** [comment]
@peterschmidt85 could you please explain what I have to do in this issue?

**Comment by wenayy** [comment]
@peterschmidt85 can you explain in more detaill so that i can work on this issue i wanna contribute

**Comment by k0msenapati** [comment]
Clarify @peterschmidt85

**Comment by peterschmidt85** [comment]
We have https://dstack.ai/examples
The idea is to add there a category "Deployment" (similar to other categories, such as Fine-tuning, Accelerators, etc.)
Under the  "Deployment"  category, we plan to add a card "TGI" which will lead to https://dstack.ai/examples/deployment/tgi - where must be an example of how to use TGI - similar and in style with other examples. What is not clear?

**Comment by peterschmidt85** [comment]
Keep in mind, if you want to work on example, this means you understand how both dstack and TGI work, and can use dstack to test the TGI example.

**Comment by peterschmidt85** [comment]
Already implemented: https://dstack.ai/examples/deployment/tgi/
