### ISSUE TITLE
[Examples] Add Airflow example

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1752]

**Comment by ayan-joshi** [comment]
@peterschmidt85 Hey I would like to work on the issue , can u explain or guide like what kind of an example should be added and where ?

**Comment by ayan-joshi** [comment]
@peterschmidt85 hey can u explain it please

**Comment by ayan-joshi** [comment]
@peterschmidt85 can u just provide info where in examples I need to add the airflow example ?
