### ISSUE TITLE
[Examples] Add TensorRT-LLM example (end-to-end)

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1753]

**Comment by bikash119** [comment]
@peterschmidt85 : May I take this up?

**Comment by peterschmidt85** [comment]
> @peterschmidt85 : May I take this up?

Only if you know how. It's not an easy one. TensorRT-LLM is one of the most complicated stacks. 
The example should show it end-to-end: how to build a model, and serve it.

**Comment by bikash119** [comment]
Will give it a stab. Will definitely be a good exercise.

**Comment by bikash119** [comment]
Thank you @peterschmidt85 for giving me the heads up. Will give it a try and keep you posted on how it goes.
May I request you to point to any example on dstack which has similar set of task like 
- build the model
- serve it

**Comment by peterschmidt85** [comment]
> Thank you @peterschmidt85 for giving me the heads up. Will give it a try and keep you posted on how it goes. May I request you to point to any example on dstack which has similar set of task like
> 
> * build the model
> * serve it

I would invite you to explore more what dstack is, how it works, and of course what TensorRT-LLM is and how it works.

**Comment by bikash119** [comment]
Thank you @peterschmidt85.
