### ISSUE TITLE
[Bug]: Dummy `Test` fleet in the webUI

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#1776]
### Steps to reproduce

1. Create at least 2 fleets.
2. Check `/fleets` page

### Actual behaviour

![image](https://github.com/user-attachments/assets/fc1c7d7f-2fcc-480b-b4ae-792f6b11f755)

### dstack version

0.18.16

### Additional information

It seems like some debug leftovers: https://github.com/dstackai/dstack/blob/fccc8dd1fc5a02a5c13c25f85761c4ed3c0f0a43/frontend/src/pages/Fleets/List/index.tsx#L50-L52

**Comment by Keerthi54654** [comment]
can i work on this

**Comment by peterschmidt85** [comment]
> can i work on this

@Keerthi54654 If you know how to fix and test it, go ahead.

**Comment by PriyanshuPz** [comment]
@un-def May I work on this issue

**Comment by PriyanshuPz** [comment]
I have fixed and tested it
Please check out @un-def 

https://github.com/user-attachments/assets/df62d102-a04f-4422-b8c4-5e8acc98bf4c

**Comment by un-def** [comment]
@priyanshuverma-dev sure, remove Draft status from your PR, and we'll merge it

**Comment by PriyanshuPz** [comment]
@un-def Got you sir.
Check again
