### ISSUE TITLE
[Examples] An example of fune-tuning with `torchtune`

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1787]
Similar to `Fine-tuning` | `TRL` and `Alignment Handbook`

**Comment by PocketTart** [comment]
Hi @peterschmidt85 , I’d like to work on this issue- An example of fune-tuning with torchtune #1787.

**Comment by peterschmidt85** [comment]
> Hi @peterschmidt85 , I’d like to work on this issue- An example of fune-tuning with torchtune #1787.

I don't see why you shouldn't

**Comment by PocketTart** [comment]
Thank you for your response, @peterschmidt85! I’m excited to work on this issue. Could you please officially assign it to me so I can begin? Let me know if there are any specific requirements or guidelines to follow. Looking forward to contributing!

**Comment by peterschmidt85** [comment]
@PocketSkye the assignment is not required. You are free to send PRs. The main requirement is that you understand what is required. If not ask questions

**Comment by austinmw** [comment]
Any updates on this? :)
