### ISSUE TITLE
[Feature]: sharing a volume in ssh fleet

### ISSUE THREAD

**Issue by deep-diver** [dstackai/dstack#1826]
### Problem

for the purpose of organizing on-premise servers, it wouldn't be necessary to download heavy files such as (~GBs of model weights) every time when a `run` is provisioned. 

### Solution

mount a volume from a machine within the same network, and make it visible to all instances in a dstack cluster.

### Workaround

no workaround for now

### Would you like to help us implement this feature by sending a PR?

No

**Comment by r4victor** [comment]
@deep-diver, we recently added support for Instance Volumes that allow you to mount volumes in SSH fleets including NFS (https://dstack.ai/docs/concepts/volumes/#network-storage-with-ssh-fleet).
