### ISSUE TITLE
Support Python 3.13, deprecate Python 3.8

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#1833]
#### Running `dstack` under 3.9-3.13

- [x] Forbid installing the `dstack` and `gpuhunt` packages under 3.8
- [ ] (optional) Upgrade the codebase to use 3.9 features
- [x] In the codebase, address removals and deprecations in 3.13, if any
- [x] Run tests under 3.9-3.13 in GitHub Actions

#### Running `dstack` configurations under 3.9-3.13
- [x] Build `dstackai/base:py3.13-*` docker images
- [x] Pre-pull `dstackai/base:py3.13-*` in dstack packer templates, do not pre-pull `dstackai/base:py3.8-*`
- [x] Allow specifying `python: 3.13` in run configurations, deprecate specifying `python: 3.8`

#### After a few `dstack` releases
- Stop building `dstackai/base:py3.8-*` docker images
- Forbid specifying `python: 3.8` in run configurations

**Comment by jvstme** [comment]
Running `dstack` under 3.13 seems to be blocked by https://github.com/MagicStack/asyncpg/issues/1181. Other steps in this issue shouldn't be blocked

**Comment by un-def** [comment]
[asyncpg v0.30.0](https://github.com/MagicStack/asyncpg/releases/tag/v0.30.0) with Python 3.13 support has just been released.

**Comment by jvstme** [comment]
Running `dstack` under 3.13 is also blocked by:
- https://github.com/zmievsa/pydantic-duality/issues/15
- https://github.com/googleapis/google-cloud-python/issues/13187

**Comment by zmievsa** [comment]
Let me take care of the first issue.
