### ISSUE TITLE
Run logs arrive corrupted

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#185]
**Describe the bug**
When running Conda install with large dependencies (pytorch) and creating artifacts out of it, occasional the run will fail with `'utf-8' codec can't decode bytes in position 4094-4095: unexpected end of data`

**Version**
 - The `dstack` CLI version: 0.1
 - The operational system version: Apple M2 MacOS 13.1
 - The Python version 3.10.4
- (Optional) Other Python packages versions (`pip freeze` or `conda list`)

**Minimal example**
Use the main branch commit https://github.com/kengz/lean-dl-example/commit/f4c06f0c59bc9d945c64bf53c7df0c26c029d67b
Run `dstack run setup-conda`

**Steps to reproduce**
Use the main branch commit https://github.com/kengz/lean-dl-example/commit/f4c06f0c59bc9d945c64bf53c7df0c26c029d67b
Run `dstack run setup-conda`
Try it multiple times since the error is random. This only happens when running it with dstack local, but never when running conda directly on user machine.

**Expected behavior**
Finish normally, which it does when rerun, so the error is random.

**Logs**
[6cda13c1f54b4a31b8e1a5038b4a4433.zip](https://github.com/dstackai/dstack/files/10716292/6cda13c1f54b4a31b8e1a5038b4a4433.zip)

**Screenshots**
Attach screenshots (if any).
<img width="732" alt="Screenshot 2023-02-12 at 9 40 56 AM" src="https://user-images.githubusercontent.com/8209263/218317703-2eca6be5-e770-43fa-9d31-e833d4c77bfc.png">

**Additional context**

**Comment by peterschmidt85** [comment]
I've seen this bug quite a few times but never was able to find what causes it or find a way to reproduce it consistently.

**Comment by peterschmidt85** [comment]
@kengz Does the workflow itself fail or the problem is only with the output?

**Comment by kengz** [comment]
The workflow fails too

**Comment by peterschmidt85** [comment]
Hmm. Are you sure? According to the runner logs, the job was marked as Done.
Just want to be sure where the problem is.

**Comment by kengz** [comment]
That's where the log ended. I had it print "done" at the end and it didn't get there.

**Comment by kengz** [comment]
went back to double check: yep the log is right, for the run named `silent-sloth-0`. <img width="545" alt="Screenshot 2023-02-12 at 4 08 14 PM" src="https://user-images.githubusercontent.com/8209263/218337201-80adb412-baba-4edb-af73-04c1f7ee3be9.png">

interestingly, `dstack ps` shows it's completed:
<img width="518" alt="Screenshot 2023-02-12 at 4 09 00 PM" src="https://user-images.githubusercontent.com/8209263/218337231-dec57667-64b8-44ce-92ef-755b45c2cdc0.png">

**Comment by r4victor** [comment]
I found the cause of the issue. dstack's runner sends logs in chunks as utf-8 websocket messages, but multibyte unicode characters can be at the boundaries of the messages causing the message to be invalid utf-8:

https://github.com/dstackai/dstack/blob/dd63876c6a954569687ca69413ee134294c68344/runner/internal/stream/http.go#L108

The solution would be to send raw bytes over websocket.

**Comment by r4victor** [comment]
@kengz, thanks for the issue. The bug will be fixed with the next release.
