### ISSUE TITLE
log not interactive on local run

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#186]
**Describe the bug**
log not interactive on local run, resulting in large amount of stdout logs

**Version**
 - The `dstack` CLI version 0.1
 - The operational system version Apple M2, MacOS 13.1
 - The Python version 3.10.4
- (Optional) Other Python packages versions (`pip freeze` or `conda list`)

**Minimal example**
Use this commit https://github.com/kengz/lean-dl-example/commit/f4c06f0c59bc9d945c64bf53c7df0c26c029d67b

**Steps to reproduce**
`dstack run setup-train` and wait till the training step.

**Expected behavior**
Training log should be interactive.

**Logs**

[ca4be51268c14b03b4fe701d6400d984.zip](https://github.com/dstackai/dstack/files/10716283/ca4be51268c14b03b4fe701d6400d984.zip)

**Screenshots**

<img width="727" alt="Screenshot 2023-02-11 at 7 44 10 PM" src="https://user-images.githubusercontent.com/8209263/218317407-8d5670aa-ad34-43f3-ba3b-a94d0612e077.png">

**Additional context**

**Comment by r4victor** [comment]
Doesn't seem to be reproducible anymore
