### ISSUE TITLE
canceling a local run takes 2 attempts

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#187]
**Describe the bug**
When doing `ctrl+C` to cancel a local run, it takes 2 attempts to actually cancel.

**Version**
 - The `dstack` CLI version 0.1
 - The operational system version Apple M2 MacOS 13.1
 - The Python version 3.10.4
- (Optional) Other Python packages versions (`pip freeze` or `conda list`)

**Minimal example**
main branch at latest commit https://github.com/kengz/lean-dl-example/commit/f4c06f0c59bc9d945c64bf53c7df0c26c029d67b

**Steps to reproduce**
`dstack run setup-train`
then press `ctrl+C` to cancel, press `y` to confirm. Need to do it twice.

**Expected behavior**
Doing it once cancels the run.

**Logs**
[e8f35343f6014f23bfbf978ab58dc6a6.zip](https://github.com/dstackai/dstack/files/10716289/e8f35343f6014f23bfbf978ab58dc6a6.zip)

**Screenshots**
<img width="645" alt="Screenshot 2023-02-11 at 7 50 16 PM" src="https://user-images.githubusercontent.com/8209263/218317592-250e4fba-b889-4080-b438-4e3fcee716eb.png">

**Additional context**

**Comment by peterschmidt85** [comment]
The same issue still occurs if I use `y` instead of `n`

<img width="496" alt="Screenshot 2023-02-22 at 13 01 04" src="https://user-images.githubusercontent.com/54148038/220667762-b9f732c3-68e4-477d-9d64-f19a57e9ea75.png">
