### ISSUE TITLE
[Feature]: Instance (aka host, local) volumes (aka mounts)

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#1894]
### Problem

Currently, the only way to share any data between runs is to use volumes, which are supported only by a small number of backends and not supported on SSH fleets at all.

If it was possible to specify an arbitrary bind mount in the run configuration — `/path/on/fleet/instance:/path/inside/run/container` (akin Docker `-v` [bind mounts](https://docs.docker.com/engine/storage/bind-mounts/)), it would be possible to at least partially work around this limitation.

Possible use cases:

* Cache shared between runs (any runs, not necessarily the same run configuration), e.g., `~/.cache/huggingface`, `~/.cache/pip`. As it’s acceptable for the software cache to be empty, it’s okay if the host directory doesn’t exist or contains irrelevant data.
* Persistent(-ish) storage. If the user is sure that nobody reuses their fleet instance, then they can use the instance mount point as some sort of persistent storage. The lifetime of such storage is bound to the lifetime of the instance.
* Network mounts that are not yet supported by `dstack` (NFS, SMB, etc.) on SSH fleet instances.

### Would you like to help us implement this feature by sending a PR?

Yes

**Comment by un-def** [comment]
Related: https://github.com/dstackai/dstack/issues/1826 https://github.com/dstackai/dstack/issues/1796

**Comment by jvstme** [comment]
Somewhat related: #1351
