### ISSUE TITLE
Unable to open dstack UI locally on Google cloud VM

### ISSUE THREAD

**Issue by sha-shrestha** [dstackai/dstack#19]
Dstack UI fails to load in a Google cloud VM - logs attached.

`DevTools failed to load SourceMap: Could not load content for https://cdn.bokeh.org/bokeh/release/bokeh.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
react-dom.production.min.js:196 TypeError: Cannot read property 'value' of undefined
    at index.js:113
    at hs (react-dom.production.min.js:198)
    at El (react-dom.production.min.js:255)
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Ya (react-dom.production.min.js:120)
    at xl (react-dom.production.min.js:254)
    at il (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Ya (react-dom.production.min.js:120)
ds @ react-dom.production.min.js:196
n.callback @ react-dom.production.min.js:210
_i @ react-dom.production.min.js:131
yi @ react-dom.production.min.js:131
_l @ react-dom.production.min.js:252
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ya @ react-dom.production.min.js:120
yl @ react-dom.production.min.js:244
il @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ya @ react-dom.production.min.js:120
Ka @ react-dom.production.min.js:121
Wa @ react-dom.production.min.js:120
el @ react-dom.production.min.js:214
Oo @ react-dom.production.min.js:163
(anonymous) @ index.js:47
(anonymous) @ actions.js:53
c @ runtime.js:63
(anonymous) @ runtime.js:293
(anonymous) @ runtime.js:118
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ actions.js:41
(anonymous) @ index.js:8
(anonymous) @ redux.js:477
S @ index.js:46
(anonymous) @ index.js:52
hs @ react-dom.production.min.js:198
El @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ya @ react-dom.production.min.js:120
xl @ react-dom.production.min.js:254
(anonymous) @ react-dom.production.min.js:254
z @ scheduler.production.min.js:17
w.port1.onmessage @ scheduler.production.min.js:14
actions.js:60 Unknown error
DevTools failed to load SourceMap: Could not load content for https://cdn.bokeh.org/bokeh/release/bokeh.min.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by sha-shrestha** [comment]
TypeError: Cannot read property 'value' of undefined
    at index.js:113
    at hs (react-dom.production.min.js:198)
    at El (react-dom.production.min.js:255)
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Ya (react-dom.production.min.js:120)
    at xl (react-dom.production.min.js:254)
    at il (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Ya (react-dom.production.min.js:120)

**Comment by peterschmidt85** [comment]
Thank you for reporting! Gonna check it shortly.
