### ISSUE TITLE
[Bug]: AWS occasionally fails to start run when using volumes and warm EC2 instance

### ISSUE THREAD

**Issue by james-boydell** [dstackai/dstack#1935]
### Steps to reproduce

-create two volumes in AWS and mounted them to dev environment
-write some data to these volumes
-stop the run. 
-while the EC2 instance is still "warm", ie, it hasn't reached the default 5 min timeout and hasn't been terminated,start a new run, same config, same volumes. It reuses the already "warm" EC2 instance. It fails... I check in AWS and the EBS volumes shows as detached.

### dstack version

0.18.21

### Server logs

```shell
`dstack._internal.server.background.tasks.process_running_job
                    s:455 shim failed to execute job jboydell-dev-0-0:
                    EXECUTOR_ERROR (prepareVolumes error: failed to mount disk:
                    exit status 32, output: mount:
                    /dstack-volumes/jboydell-cache-volume: can't read superblock
                    on /dev/nvme2n2.
                    )`
```

### Additional information

This is not consistent behaviour. If the EC2 terminates and a run has to provision a new EC2 instance, this error doesn't happen.

**Comment by un-def** [comment]
Fixed in https://github.com/dstackai/dstack/pull/1937
