### ISSUE TITLE
[Feature] Allow to attach multiple volumes based on backend and region

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1949]
**Problem:**

For example, when I use RunPod, I never know in advance if the instance I will use will be available in a particular region of my configured volume.
Thus, if I want to persist data, there is almost no convenient way given the fact that I don't know the region in advance.

**Solution:**

Allow to create volumes in multiple backends and regions, and allow to specify a list of volumes so dstack can automatically use one of them. This is a game changer feature for use cases when multiple regions (or backends) are going to be used.

```
volumes:
  - name: [my-aws-eu-west-1-volume, my-aws-us-east-1-volume]
    path: /volume_data
```

**Comment by playerzer0x** [comment]
+1. Would love to see this feature implemented ASAP. I currently have to cancel and retry different GPU + volume configurations to find one that works.
