### ISSUE TITLE
[Feature] Track disk usage with `dstack stats`

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#1950]
**Problem:**
Disk space is one of the most important factors when working with large models. Available disk space may depend on what is already downloaded, on its cache, etc. As I user I'd like to see how much space is available to understand if more space must be requested or if I need to delete cache, etc.

**Solution:**
Add `DISK used/total to `dstack stats`.

**Comment by r4victor** [comment]
Note that getting container disk usage can be an expensive operation (e.g. simply calling `docker ps --size` can take minutes). So we need to look for an efficient mechanism to report disk usage. So here's, for example, Kubernetes (cadvisor) increased disk metrics interval to 1 minute: https://github.com/google/cadvisor/pull/910.
