### ISSUE TITLE
[Bug]: dstack doesn't offer Runpod H100 GPU instances when GPU name is defined in .yml, but does when I remove it 

### ISSUE THREAD

**Issue by playerzer0x** [dstackai/dstack#1975]
### Steps to reproduce

1. I have a volume selected in my .yml and submit a request for 
```
gpu:
    count: 8
    memory: 80GB
    name: H100
```

2. I don't receive any Runpod H100 offers from dstack
3. I check the Runpod webui and see that there are H100 instances available in my volume region, with the correct quantity
4. I remove `name: H100` from my .yml but keep `memory` and `count`.
5. dstack correctly shows me an offer for H100s

### Expected behaviour

I should get the same offer with or without the GPU defined.

### dstack version

0.18.22

**Comment by jvstme** [comment]
Hi @playerzer0x, thanks for reporting. I tried different configurations but it seems to work as expected for me. If you can still reproduce this, could you please share a sample run configuration and what you see in `dstack` CLI? If you are using a volume, please also share which region it is in.

**Comment by playerzer0x** [comment]
I'm a bit strapped for time to reproduce atm, but here's a screenshot of my convo with Andrey:
![image](https://github.com/user-attachments/assets/0c36f6b7-94f7-4034-a87f-da8198a1c405)
![image](https://github.com/user-attachments/assets/ce02ecf9-1744-407f-8155-42f88d201cbc)
![image](https://github.com/user-attachments/assets/063b407b-68bc-454d-90a6-35360cc6b2e0)

The configuration/region would be the same as here (minus the start commands): https://github.com/dstackai/dstack/issues/1976#issuecomment-2477597920

**Comment by peterschmidt85** [comment]
@playerzer0x In case you see the error again on your side, lets document it as much as possible so we can dig deeper. On our side, we'll also pay attention to it.
