### ISSUE TITLE
There is no progress indicator while "dstack server start" is downloading dependencies

### ISSUE THREAD

**Issue by vaxilicaihouxian** [dstackai/dstack#2]
when i run this command:
dstack server start --port 8081

there is no output and tcp 8081 is not listening

![image](https://user-images.githubusercontent.com/8603593/90025208-66984500-dce8-11ea-9fe6-9d615d181f63.png)

**Comment by peterschmidt85** [comment]
Hi, one of the most likely reason is that it downloads the dependency. Please try to wait a bit.
If that is the case, we'll fix this in one of the updates to show a progress indicator!

**Comment by chriswweibo** [comment]
We need the progress bar, or it seems the command produces no responses.

**Comment by peterschmidt85** [comment]
Yes, gonna implement this in the next release!

**Comment by peterschmidt85** [comment]
A new version is out and it fixes this request!
