### ISSUE TITLE
[Bug]: Cannot open UI login screen

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#2018]
### Steps to reproduce

1. Start `dstack server`
2. Open a fresh session in a browser (e.g., private mode)
3. Open http://localhost:3000/

### Actual behaviour

“Welcome to dstack” message instead of login screen

![image](https://github.com/user-attachments/assets/669695bd-375a-4f30-b5f0-74e9ddd51c96)

`POST http://localhost:3000/api/auth/okta/info` returns 405 (this endpoint does not exist in dstack OSS)

![image](https://github.com/user-attachments/assets/122e6eab-d2bf-4c13-8a8d-ab13fb0f90e8)

### dstack version

0.18.26

**Comment by jvstme** [comment]
### Workaround

Go to http://localhost:3000/auth/token and sign in there
