### ISSUE TITLE
[UI] Model page code snippets fixes and improvements

### ISSUE THREAD

**Issue by un-def** [dstackai/dstack#2024]
## Bugs

Missing comma in the Python snippet:
![image](https://github.com/user-attachments/assets/d3dddd0e-b596-451f-ad5d-a640d0ec6849)

Missing part of URL in the curl snippet:
![image](https://github.com/user-attachments/assets/f217a571-3e05-4e6e-b7bf-e99f7d62f10a)

## Improvements

1. Use 4-space indentation in the Python snippet. Currently, it's a mix of 2-space and 4-space.
2. Don't use `response_format` in the curl snippet — not all implementations support it ([TGI issue](https://github.com/huggingface/text-generation-inference/issues/2523))
3. Consider adding a message example:
    Python:
    ```python
    response = client.chat.completions.create(
        ...
        messages=[
            {
                "role": "user",
                "content": "What is deep learning?",
            },
        ],
        ...
    )
    ```
    curl:
    ```
    curl http://127.0.0.1:3000/proxy/models/main/ \
      ...
      -d '{
      "model": "Llama-3.2-3B-Instruct",
      "messages": [
        {
          "role": "user",
          "content": "What is deep learning?"
        }
      ],
    ...
    ```
    Without any messages, some API implementations may return obscure error (e.g., TGI: `{"detail":"{\"error\":\"Template error: undefined value (in <string>:20)\",\"error_type\":\"template_error\"}"}`)

**Comment by jvstme** [comment]
@olgenn, thanks.
The Python sample works fine now.
For the curl sample I got this:
```shell
curl https://gateway.example.comchat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer <redacted>" \
  -d '{
  "model": "meta-llama/Meta-Llama-3.1-8B-Instruct",
  "messages": [
    {
      "role": "user",
      "content": "Hello world"
    }
  ],
  "stream": true,
  "max_tokens": 512,
}'
```
There are two issues with it:
1. The URL is invalid - there is no slash between the model's base_url (`https://gateway.example.com`) and the path (`chat/completions`). Note that some models have a trailing slash in base_url and some don't. Can we please handle both cases?
1. There is a trailing comma at the end of the JSON object (after `"max_tokens": 512`), which is not valid JSON. Can we please remove this comma?
