### ISSUE TITLE
[Bug]: Specifying --no-repo for dev environment errors

### ISSUE THREAD

**Issue by james-boydell** [dstackai/dstack#2094]
### Steps to reproduce

Try to create a dev environment , using a folder where `dstack init` has not been run. 

dstack apply -f dev-environment.yml --no-repo

### Actual behaviour

Errors with `Repo none does not exist`

### Expected behaviour

Expected to launch a dev environment with no repo and the workflow folder empty

### dstack version

0.18.30

**Comment by am001122** [comment]
Just reproduced this with a completely fresh install and the Task from the Quickstart (https://dstack.ai/docs/quickstart/#run-a-configuration). Same `dstack` version.  Everything works fine if I run `dstack init` in the same empty current working directory first.

Is it possible / supported to run `dstack` without any of the local upload / repo support?

**Comment by r4victor** [comment]
Thanks for reporting. That's definitely a bug. We'll fix it by the next release.

**Comment by am001122** [comment]
Thanks @r4victor!  Happy to test if there's a nightly / source build that fixes this as well.
