### ISSUE TITLE
[Bug]: `regions` is missing from GCP backends docs

### ISSUE THREAD

**Issue by am001122** [dstackai/dstack#2095]
### Steps to reproduce

The option to specify `regions` is not present in the docs for the GCP backend (https://dstack.ai/docs/reference/server/config.yml/#_gcp).

### Actual behaviour

It gets filled in automatically when adding a new GCP backend---this is copied from the `dstack` web console in the "Backend config" editor:
```yaml
regions: [northamerica-northeast1, northamerica-northeast2, us-central1, us-east1,
  us-east4, us-east5, us-south1, us-west1, us-west2, us-west3, us-west4, southamerica-east1,
  southamerica-west1, europe-central2, europe-north1, europe-southwest1, europe-west1,
  europe-west2, europe-west3, europe-west4, europe-west6, europe-west8, europe-west9,
  asia-east1, asia-east2, asia-northeast1, asia-northeast2, asia-northeast3, asia-south1,
  asia-south2, asia-southeast1, asia-southeast2, me-west1, australia-southeast1, australia-southeast2]
```

### Expected behaviour

Does this option to restrict the valid regions for the GCP backend actually exist in the YAML, and if so, can it be documented?

### dstack version

0.18.29

**Comment by r4victor** [comment]
@am001122, thanks for reporting. The `regions` property works but it wasn't documented. Moreover, it was missing from other backend besides GCP. Documented it and updated the docs.

**Comment by am001122** [comment]
Thanks @r4victor !
