### ISSUE TITLE
[Bug]: Instances keep running after deleting a backend

### ISSUE THREAD

**Issue by jvstme** [dstackai/dstack#2114]
### Steps to reproduce

1. Create an idle instance in a VM-based backend.
1. Delete the backend in `server/config.yml` and restart the server or delete the backend in UI.
1. Wait until the instance is terminated by termination policy.

### Actual behaviour

The instance is deleted in dstack but keeps running in the backend.

### Expected behaviour

Different options:
- Deleting the backend also deletes all the instances in the backend.
- Deleting the backend is forbidden while it still has running instances.

### dstack version

0.18.30

### Server logs

```shell
Failed to terminate the instance. Backend BackendType.TENSORDOCK is not configured in project jvstme.
```

**Comment by r4victor** [comment]
I think we should forbid deleting backends while it still has running instances. Deleting the resources automatically may lead to unintended consequences like deleting important data (e.g. volumes). Let users perform all destructive actions explicitly.
