### ISSUE TITLE
[Feature] Allow to access jobs via SSH

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#229]
Implementation notes:

1. Inside Docker containers, run an SSH server (need to discuss what certificate to use so in theory not only the user who started the job could access it but also other folks on the hub team).
2. The runner should expose the port for the SSH traffic. 
3. The runner should not expose other workflow ports.
4. If the CLI is attached to a job (e.g. `dstack run` for a single job), it should automatically forward workflow ports to `localhost`; also the CLI should output instructions on how to connect to the SSH endpoint from a terminal or any IDE.

Benefits:
1. Protecting any public ports via SSH.
2. Allows forwarding any workflow ports to localhost (make it easier to use Jupyter notebooks).
3. Allows attaching any IDEs or terminals to workflow containers.

**Comment by Egor-S** [comment]
Breaking changes:
1. All ports (except ssh) are closed
1. ssh key pair is mandatory
1. Live logs and apps could be accessed only through ssh tunnel

Subtasks:
* [x] Set path to public and private keys
* [x] Disallow all ports except ssh (GCP, AWS)
* [x] Write public key to authorized_keys in user script (GCP, AWS)
* [x] Establish ssh tunnel in subprocess for live logs and apps
* [x] Rewrite urls in logs

Running an openssh-server in a container for direct access from IDE would be a separate feature
