### ISSUE TITLE
[Feature]: Add CLI command to show runner logs

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#248]
### Problem

`dstack` users need to access runners' logs for debugging purposes. These logs are stored differently in every backend. So we have to give the users [clumsy instructions](https://docs.dstack.ai/troubleshooting/) on how to find those logs so that they can fill issues.

It's also inconvenient to search for those logs during the development process.

### Solution

Add a CLI command that outputs runner logs for the specified run. More specifically, I see two options:

1. Add a flag to `dstack logs` to show runner logs like `dstack logs --diagnose happy-bear-1 `
2. Add a totally new command like `dstack diagnose happy-bear-1`

### Benefit

* Better user experience when debugging workflow problems and filling issues.
* Better dev experience.

### Alternatives

-

### Would you like to help contributing this feature?

Yes

**Comment by dhanush-2501** [comment]
Hi there, can I work on this?
