### ISSUE TITLE
Unable to add key, value pair in Secrets

### ISSUE THREAD

**Issue by mmahesh** [dstackai/dstack#25]
I am unable to add key, value pair in Secrets.

I go through the following steps. In the end, I do not see any key, value pair (see last image).

<img width="1059" alt="fig2" src="https://user-images.githubusercontent.com/4602593/168422937-16f2ef98-46ea-4fe0-9bca-703e484c1ab1.png">

<img width="1075" alt="fig3" src="https://user-images.githubusercontent.com/4602593/168422942-253fd016-dba0-48c4-b87b-4aadf9fd9589.png">
<img width="912" alt="fig4" src="https://user-images.githubusercontent.com/4602593/168422943-2080f97e-d3c7-4ead-9754-6a98bdd7dadc.png">

**Comment by peterschmidt85** [comment]
Fixed, the problem was on the backend side
