### ISSUE TITLE
[Feature] Do not group local artifacts by repos

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#266]
Frequently, we may need to access local artifacts stored in `~/.dstack/artifacts`. This is necessary not only when running artifacts locally but also when retrieving them remotely using `dstack pull`. 

At present, the local artifacts are organized by repositories. This arrangement can be inconvenient as it requires providing the Git repository's hostname and project name before specifying the run name. However, our run names are already unique, so there is no need to use the repository host and project name as a prefix.

Currently:

`~/.dstack/artifacts/github.com/dstackai/dstack-examples/tricky-eagle-1,stable-diffusion,0`

Ideal:

`~/.dstack/artifacts/tricky-eagle-1,stable-diffusion,0`

**Comment by r4victor** [comment]
This is no longer relevant after moving to the Hub-only model (#338). Users should not work with artifacts stored in local backend directly since they can be on a different machine. Users should use CLI to get artifacts locally.
