### ISSUE TITLE
Rename `interruptible` to `spot` (in the CLI and YAML)

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#289]

**Comment by dhanush-2501** [comment]
Hey there, this is dhanush I have good knowledge of python and ml and I am a beginner at opensource can I work on this?

**Comment by peterschmidt85** [comment]
@dhanush-2501 Sure! Happy to have you onboard. This issue is perfect to start with!
Let me share a bit more context on what is the scope of the issue.
As you might've seen, all built-in providers have `interruptible` property when it comes to defining [`resources`](https://dstack.ai/docs/reference/providers/bash/#properties-reference).

Most users come to know this as "spot instances". That's why we want to rename the property to `spot`. 

Two notes:
1. We don't rename `interruptible` in other places (where we use it internally). We rename only in user-facing places.
2. All providers also provide `-i` (or `--interruptible`) flag for the `dstack run` command. Source: https://github.com/dstackai/dstack/blob/a69593be1e22388de14189766f15e4f831e806fc/cli/dstack/providers/__init__.py#L171. We need to rename this argument to `-s` (`--spot`) correspondingly.

Hope this helps.
Also, happy to help with setting up the dev environment! Please let me know if you have questions!

**Comment by dhanush-2501** [comment]
@peterschmidt85 Hey, Thanks for your help. Would definitely work on this, I didn't get notified of your response to this. that's why the delay. would work on this asap
