### ISSUE TITLE
[Feature] When uploading large files (e.g. larger than 1MB), skip if they were uploaded already (e.g. previously)

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#330]
Motivation:

When we use cache files, we upload them once the job is finished or stopped, even if they didn't change. If we cache pre-trained models from HuggingFace, these files are always pretty big (e.g. 7GB and more), and we have to wait significant additional time on each run.

**Comment by Egor-S** [comment]
We could use file size and modification time as indicators of content changes. We do not write modification time in cloud storage or local filesystem — we need to patch the runner's storage implementation for all backends.

**Comment by peterschmidt85** [comment]
We could do it (track modification time) only for the files that are larger than the threashold (to reduce the possible overhead in case of very many small files)
