### ISSUE TITLE
Reduce the number of dependencies

### ISSUE THREAD

**Issue by OlegBEZb** [dstackai/dstack#35]
There are tons of dependencies apart from the ones passed by the user. These dependencies are installed each time the run is submitted. It would be nice to optimize this part.
Ideas:

1. Select really necessary libraries
2. Make several pre-built sets for the most common use-cases

Containers from colab\kaggle would be really nice as they are +- classical and have expected behaviour regarding popular libraries

**Comment by peterschmidt85** [comment]
Implemented
