### ISSUE TITLE
dstack fails with large uncommited changes

### ISSUE THREAD

**Issue by OlegBEZb** [dstackai/dstack#42]
Regularly happens if you work with ipynb notebooks locally and going to submit a python file regardless if the latter was changed or not.
sometimes fails on the stage or `dstack run` with `requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.dstack.ai/runs/submit`
what is worse, sometimes this successfully goes to the servers but fails there without any notification

**Comment by OlegBEZb** [comment]
Received a new error `requests.exceptions.HTTPError: 413 Client Error: Request Entity Too Large for url: https://api.dstack.ai/runs/submit`

**Comment by peterschmidt85** [comment]
Is duplicated by #37
