### ISSUE TITLE
Show workflow parameters in dashboard

### ISSUE THREAD

**Issue by OlegBEZb** [dstackai/dstack#45]
<img width="294" alt="image" src="https://user-images.githubusercontent.com/28011503/170729043-99371e7c-d55f-4591-8aee-6b2bf1c91580.png">
1. apart from depends-on would be nice to have a textual representation of the dependency (name)
2. apart from run itself, it's tag may be helpful

**Comment by peterschmidt85** [comment]
Because there is no dashboard yet in the new version, we are closing this issue for now.
