### ISSUE TITLE
tag doesn't work after uploading

### ISSUE THREAD

**Issue by OlegBEZb** [dstackai/dstack#49]
using `dstack artifacts upload` I've provided the tag I wanted to assign to the data. Unfortunately, further runs depending on this data were failing without any logs. I've just removed the tag from the data (after it was successfully uploaded) and assigned it (the same tag) once again. Without any changes in the local repo, the code was resurrected and launched easily on dstack.

**Comment by peterschmidt85** [comment]
Must be fixed now
