### ISSUE TITLE
dstack 0.10.x regression test failure

### ISSUE THREAD

**Issue by chenrui333** [dstackai/dstack#490]
👋 I am trying to upgrade dstack ot the latest release, 0.10.1, but I am keep getting this weird error, can I get some help or guidance on it? Thanks!

```
The 'pygments<3.0.0,>=2.13.0' distribution was not found and is required by rich".
```

relates to https://github.com/Homebrew/homebrew-core/pull/133439

**Comment by chenrui333** [comment]
quick note, this happens for both 0.10 and 0.10.1, but not 0.9.2

**Comment by r4victor** [comment]
@chenrui333, there is no problem when installing `dstack` with pip, but only when installing the homebrew formulae. Can this be related to `pygments` being removed from resources in formulae? (https://github.com/Homebrew/homebrew-core/pull/133439/files#diff-5cdeb2b47482fef03848c35aa615c7e253c11319c3906c61d89a37b9c814b560L430)

**Comment by chenrui333** [comment]
it did not get removed, it is in the dependency list

https://github.com/Homebrew/homebrew-core/pull/133439/files#diff-5cdeb2b47482fef03848c35aa615c7e253c11319c3906c61d89a37b9c814b560L27

**Comment by r4victor** [comment]
I see it `depends_on`, but the PR removes pygments from resources. I'm not familiar enough with brew formulas to say why depends_on alone doesn't work, but after I listed pygments as a resource, the problem does not appear.

**Comment by chenrui333** [comment]
> I see it `depends_on`, but the PR removes pygments from resources. 

`depends_on` and `resource` are the two ways of declaring the dependencies, removing `pygments` from resource list is because it has already been declared in the `depends_on` list.  Let me know if that makes better sense.

**Comment by chenrui333** [comment]
I think the issue is more on the `pygments` formula setup, we have updated it and now the PR got merged, thanks anyway! 🎉 

Closing this issue now.
