### ISSUE TITLE
[Bug]: dstack repository UI still says running when ec2 instance terminated via AWS console

### ISSUE THREAD

**Issue by neonwatty** [dstackai/dstack#494]
### dstack version

0.10.1

### Python version

3.9.1 (host)

### Host OS

macOS 13.1 

### Host Arch

ARM

### What happened?

If I start a run with an `AWS` backend and terminate the ec2 instance via the `AWS console` the run still shows as running in my `dstack repositories web UI`.

This still shows as running even if I restart dstack.  

I' m not sure if this is happening with other cloud providers.

### Relevant log output

```shell
I am only seeing

~/.dstack/tmp/runner/bin 

no 

~/.dstack/tmp/runner/configs 

directory seems to exist
```

### Additional Information

See attached screen shot of my `dstack repositories UI` showing the repo as still running (when the underlying instance was terminated via the `AWS console`).

<img width="836" alt="Screen Shot 2023-06-19 at 9 50 42 AM" src="https://github.com/dstackai/dstack/assets/16326421/d97dd62f-2c87-4dfe-bf20-0a42d97a6f20">

Running `dstack ps` also shows

```bash 
 RUN               CONFIGURATION  USER   INSTANCE  STATUS                 SUBMITTED 
 green-elephant-1  .dstack.yaml   admin  m5.large  Running                yesterday 
                                                   Request(s) terminated           
```

**Comment by r4victor** [comment]
This is certainly a bug and the UI should match the CLI output. But I also suggest we change the status from Running to Failed with the error code "Instance terminated" – instead of showing a weird "Running Request(s) terminated" status.

**Comment by r4victor** [comment]
@jermwatt, thanks for the note regarding the log output. We've implemented `dstack logs --diagnose <run_name>` command that can be used to get the diagnostic logs conveniently. It'll be available in the next release.
