### ISSUE TITLE
[Feature]: make token optional with `dstack start`

### ISSUE THREAD

**Issue by neonwatty** [dstackai/dstack#504]
### Problem

Visa-vis the UI spun up via `dstack start` - it might be nice to make the `token` optional (but enabled by default).

This would make the UI bookmarkable for consistent local UI usage at localhost via

`http://127.0.0.1/:<port_num>`

### Solution

I believe that `start` is housed here

https://github.com/dstackai/dstack/blob/755f1a25b9a6185b5fa27df6c29c870cdb0e13d7/runner/main.go#L42

Is that right? 

### Benefit

This would make the UI bookmarkable for consistent local UI usage at localhost via

`http://127.0.0.1/:<port_num>`

### Alternatives

NA

### Would you like to help contributing this feature?

Yes

**Comment by r4victor** [comment]
@jermwatt , the token in the url is needed to log your in as admin when your open the link for the first time. After that, the token is saved in local storage, so you can bookmark `http://127.0.0.1/:<port_num>` and access the UI via this link without a token.

**Comment by neonwatty** [comment]
Ahh I see!  Thanks!
