### ISSUE TITLE
[Bug]: prebuild image size - too large for single object s3 upload

### ISSUE THREAD

**Issue by neonwatty** [dstackai/dstack#520]
### dstack version

10.0.2

### Python version

3.9.1

### Host OS

macOS 13.1 

### Host Arch

ARM

### What happened?

When using the new 

```dstack build```

command for pre-building, it appears that if the pre-built `.tar` image is larger than 5GB it cannot be pushed to an s3 location as this is the [maximum single object size permitted by s3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html).

Example: a dev version of the [diffusion example](https://github.com/dstackai/dstack-examples/tree/main/stable-diffusion-app) - the following `.dstack.yaml` with `requirements.txt` produces an image around `7.5GB` in size that fails to push to s3.

```yaml
type: dev-environment
build:
  - apt-get update
  - pip install -r requirements.txt
ide: vscode
```

```
diffusers
transformers
scipy
ftfy
accelerate
safetensors
```

### Relevant log output

```shell
The crucial line from running `dstack logs --diagnose <run_name` that seems to confirm that this is the issue.



[ERROR]:Failed run[err [executor.go:327 executor.(*Executor).runJob] [executor.go:809 executor.(*Executor).build] [backend.go:454 s3.(*S3).PutBuildDiff] operation error S3: PutObject, https response error StatusCode: 400, RequestID: 0MAYGFHCW85M6CGM, HostID: JzulzGTOACI0PdCwAlTp8+u45+s/ORmC/gTBNQrqjdEQm/dFpiBFL0iV7UlteknZRPsTxMkTtRU=, api error EntityTooLarge: Your proposed upload exceeds the maximum allowed size]
```
```


### Additional Information

If my understanding is correct, it appears the `.tar` pre-built image is being pushed as a single object to s3 - perhaps it can pushed in parts as outlined in [stack threads like this one](https://stackoverflow.com/questions/26319815/entitytoolarge-error-when-uploading-a-5g-file-to-amazon-s3)

**Comment by Egor-S** [comment]
@jermwatt, thanks for reporting. It's definitely a bug, we will fix it.

As a quick solution for this scenario, I suggest you use `pip install --no-cache-dir ...`. It will cut almost half of the image size.

**Comment by neonwatty** [comment]
No problem!  Not really a "bug" - a hurdle imposed by S3.   dstack is handy enough with all its other features that is not a blocker for me - I'm just being careful with what I include in the pre-build.

That (below) is a handy trick!  

```pip install --no-cache-dir ...```
