### ISSUE TITLE
Handle 5XX or 4XX error during creating/editing projects

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#548]
Currently, UI doesn't show the error message correctly if there is a 5XX or 4XX error during creating/editing projects.

It's only possible to see the error in the browser console.

Examples:

1. 422 error - e.g. if the request format is incorrect
2. 500 error - if there is an exception on the server

**Comment by r4victor** [comment]
@olgenn, let's show "Server returned 500 status code. Check server logs for more details." notification on the frontend when getting 500 on any page. For 4XX errors, let's add a generic logic so that if the frontend doesn't handle the error – it shows `body["message"]` as a notification.

**Comment by peterschmidt85** [comment]
@olgenn is this issue fixed and can be closed?
