### ISSUE TITLE
Add a list of runs from all projects and repos in UI

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#588]
Currently, it's only possible to see runs if you open a particular project and then a specific repo.
As a user, I want to be always able to see all my runs (across multiple projects and repos).
Here's what is suggested:

1. Add the `Runs` page to UI and show it by default
2. This page should show runs from all projects and repos.
3. This page should allow to filter run by a project/repo. By default, no filters are set.
4. This page should provide a toggle filter "Active runs". If enabled, the page should show only unfinished runs. It should be auto-enabled if there is at least one unfinished run.
5. It should be possible to open and run.

@olgenn Please see what changes you need from the API side, and let @r4victor know.

**Comment by olgenn** [comment]
@r4victor, we need to add api method similar `/api/project/{project_name}/runs/list`, but it have to return Runs for all projects. For example `/api/runs/list`

**Comment by olgenn** [comment]
@r4victor we need to api method for running run. For example `/api/project/{project_name}/runs/run`
