### ISSUE TITLE
[Bug]: Max duration terminates run session but does not delete cloud resources.   I was expecting resources to be deleted

### ISSUE THREAD

**Issue by joeaccelearte** [dstackai/dstack#632]
### dstack version

0.10.7

### Python version

3.11.3

### Host OS

macOS 13.2

### Host Arch

x86

### What happened?

I set up the profile below with the max_duration set to 1h.   

`dstack run --profile gpujoe . -f serve.dstack.yml --ports 8000:8000`

That command was running for 1 hour exactly then it just stopped, which is what was expected.   However, It did not delete the resources in the cloud which is what I see when I hit ctrl+c.   I was expecting the cloud resources to be deleted, I had to manually delete.  

profiles:
- name: gpujoe
  resources:
    memory: 4GB
    gpu:
      memory: 12GB
  spot_policy: auto
  max_duration: 1h
  default: true%

**Comment by peterschmidt85** [comment]
@joeaccelearte Please let me confirm a few things:
1. Which cloud resources exactly did you have to delete? 
2. Was it a task or a dev environment?
Thank you in advance!

**Comment by joeaccelearte** [comment]
> @joeaccelearte Please let me confirm a few things:
> 
> 1. Which cloud resources exactly did you have to delete?

I had to delete the whole VM in azure portal ui  that deleted the rest of the stuff like resources networks etc...  

When doing ctrl+c while task is running it will delete the VM and all other attached resources but I think it asks before deleting  "are you sure you want to delete[y/n]?".  I can't remember right now but I believe ctrl+c will ask before deleting.   

Maybe since max_duration is set  it stops the run but can not delete because it does not get confirmation? 

```shell
2023-08-09T18:23:50.067853Z  INFO HTTP request{otel.name=POST /generate http.client_ip= http.flavor=1.1 http.host=127.0.0.1:8000 http.method=POST http.route=/generate http.scheme=HTTP http.target=/generate http.user_agent=curl/7.86.0 otel.kind=server trace_id=539467c5a923ba8b62e5a0f2d99ba12e}:generate{parameters=GenerateParameters { best_of: None, temperature: None, repetition_penalty: None, top_k: None, top_p: None, typical_p: None, do_sample: false, max_new_tokens: 20, return_full_text: None, stop: [], truncate: None, watermark: false, details: false, decoder_input_details: false, seed: None } total_time="1.074548388s" validation_time="250.968µs" queue_time="37.358µs" inference_time="1.074260212s" time_per_token="53.71301ms" seed="None"}: text_generation_router::server: router/src/server.rs:289: Success
Stopped
╭─ ~/dev/dstack/quickstart  ✔  took 1h 0m 46s  dstack 3.11.3  ─╮
``` 


> 2. Was it a task or a dev environment?

It was a task:  

```shell
type: task

image: ghcr.io/huggingface/text-generation-inference:0.9.3

env:
  # (Required) Specify the name of the model
  - MODEL_ID=tiiuae/falcon-7b
  # (Optional) Specify your Hugging Face token
  - HUGGING_FACE_HUB_TOKEN=

ports:
 - 8000

commands:
  - text-generation-launcher --hostname 0.0.0.0 --port 8000 --trust-remote-code
``` 
>    Thank you in advance!

**Comment by r4victor** [comment]
@joeaccelearte, thanks for the detailed feedback. I was able to reproduce the problem. It happened to be a bug with max_duration not working properly in certain scenarios. Fixed and should not occur in the next release.
