### ISSUE TITLE
Hide local backend from the UI

### ISSUE THREAD

**Issue by r4victor** [dstackai/dstack#642]
We disable local backend support to focus on better cloud support. The local backend functionality can be implemented in the future with #4.

**Comment by radao** [comment]
Is there any simple way to re-enable the local backend? I'm just getting back to using dstack after a brief hiatus and finding this feature removed is a bit of a surprise. My use case is developing on a local GPU server with Docker and then scaling up to larger training jobs in the cloud, so the ability to easily switch from local to cloud was a huge selling point.

**Comment by peterschmidt85** [comment]
@radao Because of the heavy focus on cloud providers some time ago we decided to deprecate the local backend.
However, within a week or so we finish an important refactoring that in theory will allow us to easily add support for local backend. I'm sorry for the temporary inconvenience.
