### ISSUE TITLE
Configure gateways from project settings page

### ISSUE THREAD

**Issue by Egor-S** [dstackai/dstack#672]
Core features:

1. Show the list of existing gateways in the project
2. Delete gateway
3. Create a gateway
4. Edit gateway
    - Assign wildcard domain
    - Mark as default

Creation form:
- `backend` - select, required
- `region` - select, null value allowed

Update form:
- `default` - checkbox, null value allowed
- `wildcard_domain` - text, null value allowed

**Comment by peterschmidt85** [comment]
Also, allow to pre-select a region

**Comment by peterschmidt85** [comment]
Also, when creating a gateway, should be possible to select a primary backend
