### ISSUE TITLE
OpenSSH 8.2 with option -f in Lambda Labs freezes forever

### ISSUE THREAD

**Issue by Egor-S** [dstackai/dstack#684]
Option -f (until OpenSSH 8.4) doesn't close stdout/stderr pipes before exiting. os/exec Run in golang waits till EOF and freezes forever

Possible solutions:
- Upgrade OpenSSH
- Use files instead of the pipes for stdout/stderr
- Use WaitDelay from golang 1.20
- Interrupt Wait/Run after some delay

**Comment by peterschmidt85** [comment]
Why not use Start and ExitCode and Sleep in between?
