### ISSUE TITLE
Add logos and getting started blocks to the landing page (according to the new design)

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#69]
The sketch: https://www.figma.com/file/6lGLW1DxQlppf2k7mhlxCG/dstack?node-id=6193%3A7

**Comment by peterschmidt85** [comment]
As to Subscribe for newsletter block, let's do it in a separate task.

**Comment by olgenn** [comment]
https://gitlab.com/dstackai/dstackai-website/-/commit/f3d8ef357a86501201877ffba930079a18f3dfd2
https://gitlab.com/dstackai/dstackai-website/-/commit/a17b57ab86eecf3d661dbcfb1516eb26558676ea
