### ISSUE TITLE
Add a Python example beyond a single Python script

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#69]
So far doc shows example with a single script that can be run directly like `python train.py`. However a real project has folder structure with many `.py` files organized as module. These need to be pip-installed to be usable, for example a folder with `mnist/train.py`.

Take this folder structure for example:
<img width="208" alt="Screen Shot 2022-06-19 at 10 19 46 PM" src="https://user-images.githubusercontent.com/8209263/174513920-0e3fea4d-b97e-4260-92ad-603863b349b6.png">

Without any installation, when trying to run `python mnist/train.py` as entrypoint, the following error pops up:
```
2022-06-19 21:55 Traceback (most recent call last):
2022-06-19 21:55   File "/workflow/mnist/prepare_data.py", line 1, in <module>
2022-06-19 21:55     from mnist.train import DIR, MNISTDataModule
2022-06-19 21:55 ModuleNotFoundError: No module named 'mnist'
```

The module that is the folder `mnist/` needs to be installed with `pip install -e .` (`setup.py` file must exist first). To do this in dstack it requires adding `-e .` to `requirements.txt`, example:
```txt
pytorch-lightning
pillow
torchvision
hydra-core==1.2.0
-e .
```

Only then will it run in dstack.

**Comment by r4victor** [comment]
The new quickstart (https://github.com/dstackai/dstack/releases/tag/0.1) features such an example.
