### ISSUE TITLE
Feature to inform the frontend app user whenever the source code is changed / new app is pushed.  

### ISSUE THREAD

**Issue by riwajsapkota** [dstackai/dstack#70]
Poll the stack every second to see if its head is changed.
If it's changed, show a badge and a refresh button. Clicking the button should open the latest version (head).
The Figma sketch:

<img width="647" alt="Screenshot 2021-01-28 at 16 27 30" src="https://user-images.githubusercontent.com/54148038/106160230-e5454980-6185-11eb-9ffc-c326badddc08.png">

**Comment by peterschmidt85** [comment]
https://www.figma.com/file/6lGLW1DxQlppf2k7mhlxCG/dstack?node-id=6413%3A11
