### ISSUE TITLE
Improve resources requirements: GPU compute capability, default cpu & memory, total GPU memory

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#739]
Examples: `8.6` (Ampere), or `8.9` (Ada Lovelace), etc.

This is important, for example, when you want to run something using Flash Attention 2 (used by TGI) that requires Ampere or higher.

**Comment by Egor-S** [comment]
Additional requirements/resources features:
- Set default cpus and memory to None, so gpuhunt could fill it with reasonable values
- Add total GPU memory requirement
