### ISSUE TITLE
TensorDock server remained running even though it failed to provision

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#749]
I submitted a run to `tensordock` and it went to provision (due to some unknown problems).
After a while, server reported the run to be failed and wrote about it in the log:

```
WARNING 2023-10-30T12:38:55.795 dstack._internal.server.background.tasks.process_running_jobs Job shaggy-crab-1-0 failed because runner has not become available in time.
```

```
dstack ps -a
 RUN                     USER   BACKEND     INSTANCE                              SPOT  PRICE    STATUS      SUBMITTED
 shaggy-crab-1           admin  tensordock  0eba91f9-3c65-4755-9441-d625deab40a7  no    0.1738$  failed      19 mins ago
```

However, the server remained running in TensorDock's UI:

<img width="1239" alt="Screenshot 2023-10-30 at 12 57 01" src="https://github.com/dstackai/dstack/assets/54148038/df90ad55-062c-423b-bfb4-5f8f7e9387ab">

**Comment by r4victor** [comment]
Please re-open if reproduced.
