### ISSUE TITLE
Bundle workflow.json into the pypi artifact

### ISSUE THREAD

**Issue by chenrui333** [dstackai/dstack#784]
👋 it looks like worklfow.json is hard dependency of the formula, so maybe adding the workflow.json into the pypi source tarball (it can be done via git submodules). Let me know if that makes sense. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/130142 (I did introduce it when I did the 0.8 formula update)

**Comment by r4victor** [comment]
@chenrui333, worklfow.json is removed from dstack. I believe it's since 0.12 release.

**Comment by chenrui333** [comment]
aha, I will remove workflow.json in the homebrew formula side then. Thanks!

**Comment by chenrui333** [comment]
@r4victor can you also point me the PR or commit related to the workflow.json removal? Thanks!

**Comment by Egor-S** [comment]
@chenrui333 I believe in this one we started to store our schemas in S3 bucket
https://github.com/dstackai/dstack/commit/d30d21fd1ae0883eb98a58fa88314513e9d5a841
