### ISSUE TITLE
No module named dstack found on python 3.7 and 3.8 for dstack.cloud

### ISSUE THREAD

**Issue by riwajsapkota** [dstackai/dstack#83]
Steps to replicate 

1.   Python version = Python 3.7.9  or Python 3.8.5,  dstack version = 0.6.dev28
2.   Make sure config.yaml is set for dstack.cloud
3.  Run the test application - Minimal application from [dstack docs](https://docs.dstack.ai/quickstart)

Expected outcome

Application is pushed to dstack cloud 

Current outcome 
```
"---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-29bb7663004d> in <module>
      1 from datetime import datetime, timedelta
      2 
----> 3 import dstack.controls as ctrl
      4 import dstack as ds
      5 import plotly.graph_objects as go

ModuleNotFoundError: No module named 'dstack'"

```

**Comment by peterschmidt85** [comment]
I believe the error is on your side. It seems the current environment which you use to run the script (which pushes the application) doesn't have dstack installed.
