### ISSUE TITLE
[Feature]: Log UI Improvement

### ISSUE THREAD

**Issue by deep-diver** [dstackai/dstack#838]
### Problem

In the dashboard UI, Logs are displayed in reverse order (the oldest at the bottom). It is somewhat hard to read and unnatural

<img width="702" alt="1" src="https://github.com/dstackai/dstack/assets/26025527/0e7037b4-d438-4b91-b86b-621e1ce4dd3a">

### Solution

Reverse the order of the Log history

### Benefit

It helps reading the log in natural way, and we don't need to scroll all the way up to the top every time when refreshing 

### Alternatives

N/A

### Would you like to help contributing this feature?

No

**Comment by r4victor** [comment]
@deep-diver, thanks for reporting! Fixed it. The order should be reversed with the next dstack Cloud release.

**Comment by peterschmidt85** [comment]
~~The issue is still reproduced with 0.14.0~~ All works OK
