### ISSUE TITLE
run fails if local git is diverged from remote

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#86]
steps to reproduce:
- modify local commit so that it diverges
- check `git status` yields a message similar to:
```
Your branch and 'origin/default-resume' have diverged,
and have 1 and 1 different commits each, respectively.
```
- run dstack, and it fails directly without logs. example runs below.

<img width="1250" alt="Screen Shot 2022-07-11 at 10 18 50 PM" src="https://user-images.githubusercontent.com/8209263/178394404-e8df3ac6-6ace-406f-b986-e1bbd81108c6.png">

**Comment by peterschmidt85** [comment]
@kengz I fixed this issue recently. Could you please check that the problem is present with the latest version of the CLI?

**Comment by kengz** [comment]
feel free to close
