### ISSUE TITLE
[Feature]: Show the AWS region on launched instances

### ISSUE THREAD

**Issue by tleyden** [dstackai/dstack#866]
### Problem

When I launch an instance via dstack into AWS, I have to go hunting around the AWS console to find where it got launched.  This makes it too easy to lose track of instances.

### Solution

Show which AWS region instances reside in

### Benefit

Solves the problem

### Alternatives

Fix the AWS UI to show a collapsed view across regions (j/k)

### Would you like to help contributing this feature?

No

**Comment by peterschmidt85** [comment]
A question, would it be OK if `dstack` uses its own unified region codes that would map to each provider?

See https://github.com/dstackai/gpuhunt/issues/23

**Comment by tleyden** [comment]
Yeah that's fine.  It seems like the mapping should be pretty obvious in most cases.  

There should be some documentation to show all the mappings, or a command line flag to automatically translate it into the appropriate cloud region.

**Comment by peterschmidt85** [comment]
Mus be fixed now
