### ISSUE TITLE
Allow to configure VPC for an AWS backend via `~/.dstack/server/config.yml` 

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#876]
This is important when a) there is no default VPC; b) the user wants to use a non-default VPC

**Comment by r4victor** [comment]
Here's the proposal to add support for non-default VPC for AWS.

First, allow to specify a VPC name in `/server/config.yml` like so:

```
backends:
  - type: aws
    vpc: test-vpc
    creds:
      type: default
```

dstack will then launch new instances in the specified VPC. If the VPC is missing in some region, the region will be skipped.

If required, we may later support specifying different VPCs for different regions.

Implementation details:

There is no way to specify vpc_id directly when launching AWS instances, only subnet_id. So dstack should determine the subnet for the VPC automatically. For example, we can take any subnet at random. More elaborate implementation may require an additional subnet filtering such as checking if the subnet is public.

**Comment by peterschmidt85** [comment]
- [ ] Mention VPC in the `Installation` documentation

**Comment by peterschmidt85** [comment]
> vpc: test-vpc

@r4victor Let's please rename the property to `vpc_name` for better redability.

**Comment by r4victor** [comment]
> > vpc: test-vpc
> 
> @r4victor Let's please rename the property to `vpc_name` for better redability.

Done
