### ISSUE TITLE
[Feature]: Allow to specify regions in `dstack run` and `.dstack/profiles.yml`

### ISSUE THREAD

**Issue by tleyden** [dstackai/dstack#877]
Currently when launching an instance via the CLI, there is no way to specify a region, it can only be controlled via a config file.

It might be nice to save a config file edit by overriding the region via CLI param.

**Comment by r4victor** [comment]
@tleyden, thanks for the issue. We're considering adding this feature.

We can allow specifying cloud-specific regions by passing `-r/--region` to `dstack run` like so

```
dstack run . -r us-east-1 -r us-east-2
```

dstack will provision the instance in one of the regions specified. If `-r/--region` is not specified, all regions configured for the backend will be considered. 

If multiple backends are configured, users would need to specify cloud-specific regions for every backend. E.g. separately for aws and gcp:

```
dstack run . -r us-east-1 -r us-east1
```

 To simplify this, we may introduce aliases for popular regions that would map to cloud-specific regions. For example:
 
 * north-america -> us-east-1, , ca-central-1, us-east1, ...
 * south-america -> ...
 * europe -> ...
 * asia -> ...
 * australia -> ...
 * us -> ...
 * east-us -> ...
 
 So users can run:
 
 ```
dstack run . -r us
```

Implementation details:

To support specifying regions for the run, we can extend [Requirements](https://github.com/dstackai/dstack/blob/8d5b7353c55aaebf49b7b015545305df68fa9d54/src/dstack/_internal/core/models/runs.py#L70) with regions field. Then for every backend [Compute.get_offers()](https://github.com/dstackai/dstack/blob/8d5b7353c55aaebf49b7b015545305df68fa9d54/src/dstack/_internal/core/backends/base/compute.py#L26) should take regions into account when filtering offers.

To support unified regions, each backend would need to implement mapping from dstack regions to cloud-regions. We should make it a separate issue.

**Comment by peterschmidt85** [comment]
In `0.17.0`, `dstack` will allow to specify cloud-specific region codes via CLI and API.
Later (e.g. in `0.18.0`, we'll allow to specify regions via cross-clouds aliases), see https://github.com/dstackai/dstack/issues/877#issuecomment-1931782877.

**Comment by peterschmidt85** [comment]
@r4victor Shall we re-open the issue as aliases aren't implemented? Or shall we create another issue for aliases?

**Comment by r4victor** [comment]
@peterschmidt85, this issue is completed. Regarding the aliases, there is an open issue already (see #948).
