### ISSUE TITLE
Dependencies tutorial: ModuleNotFoundError: No module named 'faker'

### ISSUE THREAD

**Issue by riwajsapkota** [dstackai/dstack#89]
Steps to reproduce 

1. Follow the tutorial as mentioned in https://github.com/dstackai/dstack-examples/tree/master/deps_app
2. Make sure to run dstack v29 in windows 10. 
3. Ran dstack locally - `dstack server start`
3. Ran the script app.py from deps_app folder. 

The following error was recorded 
`
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from handlers import fake_handler
  File "C:\Users\riwaj\deps_app\handlers.py", line 3, in <module>
    from utils.fake_utils import random_names, random_genders, random_dates
  File "C:\Users\riwaj\deps_app\utils\fake_utils.py", line 3, in <module>
    from faker.providers.person.en import Provider
ModuleNotFoundError: No module named 'faker'
` 

![image](https://user-images.githubusercontent.com/51491390/104516673-0a1db680-55f5-11eb-82b9-258441b0c831.png)

**Comment by peterschmidt85** [comment]
The problem is in your local environment. You don’t have faker installed locally.
Run “pip install faker==5.5.0” locally
