### ISSUE TITLE
Keep current output until new one is available. Add Reset Button.

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#90]
1. Currently, if any control is changed by the user, the previous output disappears. Let's keep it until the user clicks Apply.
2. Let's add a Reset button (as another control). It must be enabled as soon as the user changed any control or clicked Apply. Reset Button opens the application in its initial state (execute with no parameters).

**Comment by iromeo** [comment]
I expect the same behavior in case of multiple tabs, e.g. if I switch back to the prev tab, I'll see the tab's rendered result immediately, w/o recalculation.

**Comment by peterschmidt85** [comment]
Also, in this case, let's add execution_id to URL even if there Is no output! - Basically on any change.
