### ISSUE TITLE
need complete workflow file syntax documentation

### ISSUE THREAD

**Issue by kengz** [dstackai/dstack#91]
Currently the workflow file doc https://docs.dstack.ai/workflows/#workflows-file-syntax syntax coverage is not complete. The doc needs to list all the keys available, plus example values and variations/usage. For example,
```
      gpu:
        name: "K80"
        count: 4
```
This shows up in the providers [example doc](https://docs.dstack.ai/providers/bash/) but not the workflows syntax doc.

**Comment by peterschmidt85** [comment]
We've added more examples now: https://docs.dstack.ai/examples/resources
