### ISSUE TITLE
Update Contribution Guide `How-to-add-a-backend` for Clarity and Efficiency

### ISSUE THREAD

**Issue by KevKibe** [dstackai/dstack#915]
### Problem

Contribution guide [How-to-add-a-backend](https://github.com/dstackai/dstack/wiki/How-to-add-a-backend) not very clear and descriptive.

### Solution

I've proposed some updates to the contribution guide [How-to-add-a-backend](https://github.com/dstackai/dstack/wiki/How-to-add-a-backend) to enhance clarity and make the process more efficient for new contributors. 

### Benefit

Will make the process more efficient for new contributors. 

### Alternatives

None

### Would you like to help contributing this feature?

Yes

**Comment by peterschmidt85** [comment]
Thanks a lot for creating the issue! Looking forward to your contribution and happy to help along the way! 

BTW, it can be a great idea to use this issue to collect all the feedback about the process of implementing a custom backend.

**Comment by KevKibe** [comment]
The contribution is ready https://github.com/KevKibe/dstack/wiki/How-to-add-a-backend , I don't think I can submit a PR for wikis.
Moving onto implementing a custom backend next.

**Comment by peterschmidt85** [comment]
@KevKibe We've moved the wiki page to https://github.com/dstackai/dstack/blob/master/contributing/BACKENDS.md.
Please check it and submit the PR.
If possible, please add to the PR, a short list of what has changed.

**Comment by KevKibe** [comment]
@peterschmidt85 Have you considered adding [paperspace](https://www.paperspace.com/) as a backend before?
Looking through their [documentation](https://docs.digitalocean.com/products/paperspace/) they don't have a Python SDK for all their services but they have cURL SDK covering all bases, that would work with Python using the subprocess library.

**Comment by peterschmidt85** [comment]
> Have you considered adding [paperspace](https://www.paperspace.com/) as a backend before?

Yes, here's the whole list of potential providers: FluidStack, RunPod, Scaleway, Oracle, Alibaba Cloud, CoreWeave, Latitude, Oblivus, OVH, Tencent, IBM, Paperspace.

Please feel free to choose any and let me know! Happy to help with any questions along the way!

**Comment by KevKibe** [comment]
@peterschmidt85 Looking through the Paperspace documentation, I can determine the [availability](https://docs.digitalocean.com/reference/paperspace/core/commands/machines/#availability) of a VM(with a GPU) through a Boolean value,  requiring the machine type and region as inputs. 
For pricing and machine specs, I'll need to implement web scraping of this [page](https://docs.digitalocean.com/products/paperspace/machines/details/pricing/) similar to the implementation of Nebius.
My approach is to compile a list of machine types(11) and regions(3) and then iterate through each combination to identify which machines are available, for those that are, return their specifications alongside the pricing information

**Comment by peterschmidt85** [comment]
@KevKibe 
> For pricing and machine specs, I'll need to implement web scraping of this [page](https://docs.digitalocean.com/products/paperspace/machines/details/pricing/) similar to the implementation of Nebius.

IMO web scraping is a bad idea and we don't use it anymore. The Nebius's code is legacy.
I'd suggest hard-coding the prices. This is a lot more stable.

Please let me know if any help is needed!

**Comment by rdvo** [comment]
anyone ever finish paperspace integraton they have come good compue prices
