### ISSUE TITLE
Connecting Github to dstack cloud

### ISSUE THREAD

**Issue by aniketwattamwar** [dstackai/dstack#92]
Is there any way that I can connect my GitHub repository and from there publish my app to dstack cloud ?
If this is possible then I can have version control on the app that I will be creating.

**Comment by peterschmidt85** [comment]
@aniketwattamwar Until this feature is implemented, it's recommended that you use your own GitHub Action workflow to deploy the new version of the application on every push. Please let me know if you have any questions.
