### ISSUE TITLE
[Bug]: The SSH tunnel fails with `Too many authentication failures`

### ISSUE THREAD

**Issue by spott** [dstackai/dstack#927]
Steps to reproduce:

1. Have multiple identity files under `~/.ssh` (e.g. more than 30)
2. Run `dstack server`
3. Define `.dstack.yml`
4. Run `dstack run .`

The server fails with 

```
Warning: Permanently added '192.18.137.190' (ED25519) to the list of known hosts.\r\nReceived disconnect from 192.18.137.190 port 22:2: Too many authentication failures\r\nDisconnected from 192.18.137.190 port 22\r\n
```

A possible reason:

The server, when [establishing an SSH tunnel](https://github.com/dstackai/dstack/blob/master/src/dstack/_internal/core/services/ssh/tunnel.py) doesn't specify the identity file. Because of that, `ssh` tries all identity files in sequence [resulting in the error](https://superuser.com/questions/268776/how-do-i-configure-ssh-so-it-doesnt-try-all-the-identity-files-automatically).

**Comment by peterschmidt85** [comment]
Gonna be fixed in 0.16.1
