### ISSUE TITLE
[UX] Make `commands` optional for tasks and services (and let use the default Docker image entrypoint)

### ISSUE THREAD

**Issue by peterschmidt85** [dstackai/dstack#938]
Currently, the `commands` property is required for task and service configurations.

Often, the user may need to use a Docker image that already has the default entry point configured.

## Workaround

1. Ensure you pass `commands`
2. Ensure you set the `working_dir` properly. By default, `dstack` sets it to `/workflow` where it mounts the repos' code (if any).

**Comment by r4victor** [comment]
So the idea is: if `commands` is not specified, run the default ENTRYPOINT + CMD defined by the custom image. Still, there will be no way to run the default ENTRYPOINT with `commands` specified? @peterschmidt85, please confirm if my understanding is correct.

**Comment by peterschmidt85** [comment]
@r4victor Yup, if `commands` is not specified, it means, 
1) `dstack` uses the image's entrypoint
2) `dstack` uses the image's working directory

**Comment by r4victor** [comment]
Regarding the implementation, in case of a VM backend, we could simply inspect docker image after pulling to get the default ENTRYPOINT and CMD. But in case of a Container backend, this approach is not possible. Alternatively we could use Docker HTTP API V2 to get image metadata without pulling but it's still a question of whether it works on all/most container registries.

**Comment by peterschmidt85** [comment]
My 2 personal cents:

**Solution 1: Require the user to specify either `commands` or `entrypoint`**

If the user has specified `entrypoint`, then `dstack-runner` executes it using the Image's default working directory.

Pros:
- This is easy to implement. 
- This makes the contract for the user more clear: `commands` - override the entrypoint and working directory; `entrypoint` must always be set by the user.

Cons:
- It's very inconvenient to set `entrypoint` manually by the user - because often it's very hard to know without manually pulling the image.

**Solution 2: Make both `commands` and `entrypoint` optional** 

2.1. For VM-based providers, let `dstack-shim` retrieve the entrypoint automatically after pulling the image

2.2. For container-based providers, let `dstack-runner` retrieve the entrypoint automatically via the registry API (e.g. via [crane](https://explore.ggcr.dev/?image=ghcr.io%2Fmistralai%2Fmistral-src%2Fvllm))

Pros:
 - Theoretically, if [`crane`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/README.md) works, this solves the issue entirely

Cons:
 - We must ensure that `crane`'s Go library can be invoked from `dstack-runner` without any issues. 
 
> Note, if `crane` is invoked from `dstack-runner`, we have to pass `registry_auth` inside the container. A better alternative for that could be invoking `crane` from the server – but that would require adding `crane` to the dependencies.

**Comment by jvstme** [comment]
The final solution is:
- If a custom `image` is specified in the run configuration, both `commands` and `entrypoint` are optional.
- If neither `commands` nor `entrypoint` is specified, the server retrieves the image's manifest from the docker registry and uses the image's `ENTRYPOINT`+ `CMD`.
- If the image has no default `ENTRYPOINT` or `CMD`, the user is requested to specify either `commands` or `entrypoint`.
- If `commands` is not specified, the image's default working directory is used.
