### ISSUE TITLE
Need ability to choose disk size for vastai instead of the hardcoded 80GB

### ISSUE THREAD

**Issue by iRohith** [dstackai/dstack#973]

**Comment by r4victor** [comment]
@iRohith, I'm not sure I understand what "hardcoded 80GB" is referring to. Can you please point in the code where the hardcode is and what it affects?

**Comment by iRohith** [comment]
@r4victor It is hard coded here
https://github.com/dstackai/dstack/blob/28a72b170cbe77c034dbae1a3f9b94972350d7dc/src/dstack/_internal/core/backends/vastai/api_client.py#L12.
Other providers like aws. gcp, azure create an instance with specific disk size when we specify disk size in requirements but not vast ai. It shows no offers when we specify exact disk size.

**Comment by r4victor** [comment]
Got it! Will take care of it.
